// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.FieldOptions.EditionDefault(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB.FieldOptions_PB {

    [System.Serializable]
    public class EditionDefault {
    
        public string edition;
        public global::Google_PB.Protobuf_PB.Edition edition_Enum
        {
            get => global::Google_PB.Protobuf_PB.Edition_String.ToEnum(edition);
            set => edition = global::Google_PB.Protobuf_PB.Edition_String.FromEnum(value);
        }
        public long edition_Long
        {
            get => global::Google_PB.Protobuf_PB.Edition_String.ToLong(edition);
            set => edition = global::Google_PB.Protobuf_PB.Edition_String.FromLong(value);
        }
        
        public string value;
        
    }

}