// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.FieldOptions.JSType(google/protobuf/descriptor.proto)
// </auto-generated>



namespace Google_PB.Protobuf_PB.FieldOptions_PB {

    public enum Jstype {
    
        JsNormal = 0,
    
        JsString = 1,
    
        JsNumber = 2,
    
    }
    public class Jstype_String {
        public static string FromEnum(global::Google_PB.Protobuf_PB.FieldOptions_PB.Jstype enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.Jstype.JsNormal:
                    return "JS_NORMAL";
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.Jstype.JsString:
                    return "JS_STRING";
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.Jstype.JsNumber:
                    return "JS_NUMBER";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static string FromLong(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "JS_NORMAL";
            
                case 1:
                    return "JS_STRING";
            
                case 2:
                    return "JS_NUMBER";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.FieldOptions_PB.Jstype ToEnum(string stringValue) {
            switch (stringValue) {
            
                case "JS_NORMAL":
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.Jstype.JsNormal;
            
                case "JS_STRING":
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.Jstype.JsString;
            
                case "JS_NUMBER":
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.Jstype.JsNumber;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static long ToLong(string stringValue) {
            switch (stringValue) {
            
                case "JS_NORMAL":
                    return 0;
            
                case "JS_STRING":
                    return 1;
            
                case "JS_NUMBER":
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
    
        public const string JsNormal = "JS_NORMAL";
    
        public const string JsString = "JS_STRING";
    
        public const string JsNumber = "JS_NUMBER";
    
    }

    public class Jstype_Long {
        public static long FromEnum(global::Google_PB.Protobuf_PB.FieldOptions_PB.Jstype enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.Jstype.JsNormal:
                    return 0;
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.Jstype.JsString:
                    return 1;
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.Jstype.JsNumber:
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static long FromString(string stringValue) {
            switch (stringValue) {
            
                case "JS_NORMAL":
                    return 0;
            
                case "JS_STRING":
                    return 1;
            
                case "JS_NUMBER":
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.FieldOptions_PB.Jstype ToEnum(long longValue) {
            switch (longValue) {
            
                case 0:
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.Jstype.JsNormal;
            
                case 1:
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.Jstype.JsString;
            
                case 2:
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.Jstype.JsNumber;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static string ToString(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "JS_NORMAL";
            
                case 1:
                    return "JS_STRING";
            
                case 2:
                    return "JS_NUMBER";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
    
        public const long JsNormal = 0;
    
        public const long JsString = 1;
    
        public const long JsNumber = 2;
    
    }
}