// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.JwtPayload.AccessData(api/v1/jwt.proto)
// </auto-generated>

namespace Api_PB.V1_PB.JwtPayload_PB {

    [System.Serializable]
    public class AccessData {
    
        public string sessionId;
        
        public string userId;
        
        public string authenticationId;
        
        public string role;
        
        public global::System.Collections.Generic.List<string> scopes;
        
    }

}