// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.JwtPayload.JwtKind(api/v1/jwt.proto)
// </auto-generated>



namespace Api_PB.V1_PB.JwtPayload_PB {

    public enum JwtKind {
    
        JwtKindUnspecified = 0,
    
        JwtKindAccess = 20,
    
        JwtKindRefresh = 21,
    
    }
    public class JwtKind_String {
        public static string FromEnum(global::Api_PB.V1_PB.JwtPayload_PB.JwtKind enumValue) {
            switch (enumValue) {
            
                case global::Api_PB.V1_PB.JwtPayload_PB.JwtKind.JwtKindUnspecified:
                    return "JWT_KIND_UNSPECIFIED";
            
                case global::Api_PB.V1_PB.JwtPayload_PB.JwtKind.JwtKindAccess:
                    return "JWT_KIND_ACCESS";
            
                case global::Api_PB.V1_PB.JwtPayload_PB.JwtKind.JwtKindRefresh:
                    return "JWT_KIND_REFRESH";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static string FromLong(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "JWT_KIND_UNSPECIFIED";
            
                case 20:
                    return "JWT_KIND_ACCESS";
            
                case 21:
                    return "JWT_KIND_REFRESH";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static global::Api_PB.V1_PB.JwtPayload_PB.JwtKind ToEnum(string stringValue) {
            switch (stringValue) {
            
                case "JWT_KIND_UNSPECIFIED":
                    return global::Api_PB.V1_PB.JwtPayload_PB.JwtKind.JwtKindUnspecified;
            
                case "JWT_KIND_ACCESS":
                    return global::Api_PB.V1_PB.JwtPayload_PB.JwtKind.JwtKindAccess;
            
                case "JWT_KIND_REFRESH":
                    return global::Api_PB.V1_PB.JwtPayload_PB.JwtKind.JwtKindRefresh;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static long ToLong(string stringValue) {
            switch (stringValue) {
            
                case "JWT_KIND_UNSPECIFIED":
                    return 0;
            
                case "JWT_KIND_ACCESS":
                    return 20;
            
                case "JWT_KIND_REFRESH":
                    return 21;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
    
        public const string JwtKindUnspecified = "JWT_KIND_UNSPECIFIED";
    
        public const string JwtKindAccess = "JWT_KIND_ACCESS";
    
        public const string JwtKindRefresh = "JWT_KIND_REFRESH";
    
    }

    public class JwtKind_Long {
        public static long FromEnum(global::Api_PB.V1_PB.JwtPayload_PB.JwtKind enumValue) {
            switch (enumValue) {
            
                case global::Api_PB.V1_PB.JwtPayload_PB.JwtKind.JwtKindUnspecified:
                    return 0;
            
                case global::Api_PB.V1_PB.JwtPayload_PB.JwtKind.JwtKindAccess:
                    return 20;
            
                case global::Api_PB.V1_PB.JwtPayload_PB.JwtKind.JwtKindRefresh:
                    return 21;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static long FromString(string stringValue) {
            switch (stringValue) {
            
                case "JWT_KIND_UNSPECIFIED":
                    return 0;
            
                case "JWT_KIND_ACCESS":
                    return 20;
            
                case "JWT_KIND_REFRESH":
                    return 21;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static global::Api_PB.V1_PB.JwtPayload_PB.JwtKind ToEnum(long longValue) {
            switch (longValue) {
            
                case 0:
                    return global::Api_PB.V1_PB.JwtPayload_PB.JwtKind.JwtKindUnspecified;
            
                case 20:
                    return global::Api_PB.V1_PB.JwtPayload_PB.JwtKind.JwtKindAccess;
            
                case 21:
                    return global::Api_PB.V1_PB.JwtPayload_PB.JwtKind.JwtKindRefresh;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static string ToString(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "JWT_KIND_UNSPECIFIED";
            
                case 20:
                    return "JWT_KIND_ACCESS";
            
                case 21:
                    return "JWT_KIND_REFRESH";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
    
        public const long JwtKindUnspecified = 0;
    
        public const long JwtKindAccess = 20;
    
        public const long JwtKindRefresh = 21;
    
    }
}