// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.DescriptorProto(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB {

    public class DescriptorProto {
    
        public string name;
        
        public global::System.Collections.Generic.List<global::Google_PB.Protobuf_PB.FieldDescriptorProto> field;
        
        public global::System.Collections.Generic.List<global::Google_PB.Protobuf_PB.FieldDescriptorProto> extension;
        
        public global::System.Collections.Generic.List<global::Google_PB.Protobuf_PB.DescriptorProto> nestedType;
        
        public global::System.Collections.Generic.List<global::Google_PB.Protobuf_PB.EnumDescriptorProto> enumType;
        
        public global::System.Collections.Generic.List<global::Google_PB.Protobuf_PB.DescriptorProto_PB.ExtensionRange> extensionRange;
        
        public global::System.Collections.Generic.List<global::Google_PB.Protobuf_PB.OneofDescriptorProto> oneofDecl;
        
        public global::Google_PB.Protobuf_PB.MessageOptions options;
        
        public global::System.Collections.Generic.List<global::Google_PB.Protobuf_PB.DescriptorProto_PB.ReservedRange> reservedRange;
        
        public global::System.Collections.Generic.List<string> reservedName;
        
    }

}