// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.EnumDescriptorProto(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB {

    public class EnumDescriptorProto {
    
        public string name;
        
        public global::System.Collections.Generic.List<global::Google_PB.Protobuf_PB.EnumValueDescriptorProto> value;
        
        public global::Google_PB.Protobuf_PB.EnumOptions options;
        
        public global::System.Collections.Generic.List<global::Google_PB.Protobuf_PB.EnumDescriptorProto_PB.EnumReservedRange> reservedRange;
        
        public global::System.Collections.Generic.List<string> reservedName;
        
    }

}