// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.EnumOptions(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB {

    [System.Serializable]
    public class EnumOptions {
    
        public bool allowAlias;
        
        public bool deprecated;
        
        public bool deprecatedLegacyJsonFieldConflicts;
        
        public global::Google_PB.Protobuf_PB.FeatureSet features;
        
        public global::System.Collections.Generic.List<global::Google_PB.Protobuf_PB.UninterpretedOption> uninterpretedOption;
        
    }

}