// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.ExtensionRangeOptions(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB {

    [System.Serializable]
    public class ExtensionRangeOptions {
    
        public global::System.Collections.Generic.List<global::Google_PB.Protobuf_PB.UninterpretedOption> uninterpretedOption;
        
        public global::System.Collections.Generic.List<global::Google_PB.Protobuf_PB.ExtensionRangeOptions_PB.Declaration> declaration;
        
        public global::Google_PB.Protobuf_PB.FeatureSet features;
        
        public string verification;
        public global::Google_PB.Protobuf_PB.ExtensionRangeOptions_PB.VerificationState verification_Enum
        {
            get => global::Google_PB.Protobuf_PB.ExtensionRangeOptions_PB.VerificationState_String.ToEnum(verification);
            set => verification = global::Google_PB.Protobuf_PB.ExtensionRangeOptions_PB.VerificationState_String.FromEnum(value);
        }
        public long verification_Long
        {
            get => global::Google_PB.Protobuf_PB.ExtensionRangeOptions_PB.VerificationState_String.ToLong(verification);
            set => verification = global::Google_PB.Protobuf_PB.ExtensionRangeOptions_PB.VerificationState_String.FromLong(value);
        }
        
    }

}