// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.FeatureSetDefaults(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB {

    public class FeatureSetDefaults {
    
        public global::System.Collections.Generic.List<global::Google_PB.Protobuf_PB.FeatureSetDefaults_PB.FeatureSetEditionDefault> defaults;
        
        public string minimumEdition;
        public global::Google_PB.Protobuf_PB.Edition minimumEdition_Enum
        {
            get => global::Google_PB.Protobuf_PB.Edition_String.ToEnum(minimumEdition);
            set => minimumEdition = global::Google_PB.Protobuf_PB.Edition_String.FromEnum(value);
        }
        public long minimumEdition_Long
        {
            get => global::Google_PB.Protobuf_PB.Edition_String.ToLong(minimumEdition);
            set => minimumEdition = global::Google_PB.Protobuf_PB.Edition_String.FromLong(value);
        }
        
        public string maximumEdition;
        public global::Google_PB.Protobuf_PB.Edition maximumEdition_Enum
        {
            get => global::Google_PB.Protobuf_PB.Edition_String.ToEnum(maximumEdition);
            set => maximumEdition = global::Google_PB.Protobuf_PB.Edition_String.FromEnum(value);
        }
        public long maximumEdition_Long
        {
            get => global::Google_PB.Protobuf_PB.Edition_String.ToLong(maximumEdition);
            set => maximumEdition = global::Google_PB.Protobuf_PB.Edition_String.FromLong(value);
        }
        
    }

}