// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.FeatureSet(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB {

    [System.Serializable]
    public class FeatureSet {
    
        public string fieldPresence;
        public global::Google_PB.Protobuf_PB.FeatureSet_PB.FieldPresence fieldPresence_Enum
        {
            get => global::Google_PB.Protobuf_PB.FeatureSet_PB.FieldPresence_String.ToEnum(fieldPresence);
            set => fieldPresence = global::Google_PB.Protobuf_PB.FeatureSet_PB.FieldPresence_String.FromEnum(value);
        }
        public long fieldPresence_Long
        {
            get => global::Google_PB.Protobuf_PB.FeatureSet_PB.FieldPresence_String.ToLong(fieldPresence);
            set => fieldPresence = global::Google_PB.Protobuf_PB.FeatureSet_PB.FieldPresence_String.FromLong(value);
        }
        
        public string enumType;
        public global::Google_PB.Protobuf_PB.FeatureSet_PB.EnumType enumType_Enum
        {
            get => global::Google_PB.Protobuf_PB.FeatureSet_PB.EnumType_String.ToEnum(enumType);
            set => enumType = global::Google_PB.Protobuf_PB.FeatureSet_PB.EnumType_String.FromEnum(value);
        }
        public long enumType_Long
        {
            get => global::Google_PB.Protobuf_PB.FeatureSet_PB.EnumType_String.ToLong(enumType);
            set => enumType = global::Google_PB.Protobuf_PB.FeatureSet_PB.EnumType_String.FromLong(value);
        }
        
        public string repeatedFieldEncoding;
        public global::Google_PB.Protobuf_PB.FeatureSet_PB.RepeatedFieldEncoding repeatedFieldEncoding_Enum
        {
            get => global::Google_PB.Protobuf_PB.FeatureSet_PB.RepeatedFieldEncoding_String.ToEnum(repeatedFieldEncoding);
            set => repeatedFieldEncoding = global::Google_PB.Protobuf_PB.FeatureSet_PB.RepeatedFieldEncoding_String.FromEnum(value);
        }
        public long repeatedFieldEncoding_Long
        {
            get => global::Google_PB.Protobuf_PB.FeatureSet_PB.RepeatedFieldEncoding_String.ToLong(repeatedFieldEncoding);
            set => repeatedFieldEncoding = global::Google_PB.Protobuf_PB.FeatureSet_PB.RepeatedFieldEncoding_String.FromLong(value);
        }
        
        public string utf8Validation;
        public global::Google_PB.Protobuf_PB.FeatureSet_PB.Utf8Validation utf8Validation_Enum
        {
            get => global::Google_PB.Protobuf_PB.FeatureSet_PB.Utf8Validation_String.ToEnum(utf8Validation);
            set => utf8Validation = global::Google_PB.Protobuf_PB.FeatureSet_PB.Utf8Validation_String.FromEnum(value);
        }
        public long utf8Validation_Long
        {
            get => global::Google_PB.Protobuf_PB.FeatureSet_PB.Utf8Validation_String.ToLong(utf8Validation);
            set => utf8Validation = global::Google_PB.Protobuf_PB.FeatureSet_PB.Utf8Validation_String.FromLong(value);
        }
        
        public string messageEncoding;
        public global::Google_PB.Protobuf_PB.FeatureSet_PB.MessageEncoding messageEncoding_Enum
        {
            get => global::Google_PB.Protobuf_PB.FeatureSet_PB.MessageEncoding_String.ToEnum(messageEncoding);
            set => messageEncoding = global::Google_PB.Protobuf_PB.FeatureSet_PB.MessageEncoding_String.FromEnum(value);
        }
        public long messageEncoding_Long
        {
            get => global::Google_PB.Protobuf_PB.FeatureSet_PB.MessageEncoding_String.ToLong(messageEncoding);
            set => messageEncoding = global::Google_PB.Protobuf_PB.FeatureSet_PB.MessageEncoding_String.FromLong(value);
        }
        
        public string jsonFormat;
        public global::Google_PB.Protobuf_PB.FeatureSet_PB.JsonFormat jsonFormat_Enum
        {
            get => global::Google_PB.Protobuf_PB.FeatureSet_PB.JsonFormat_String.ToEnum(jsonFormat);
            set => jsonFormat = global::Google_PB.Protobuf_PB.FeatureSet_PB.JsonFormat_String.FromEnum(value);
        }
        public long jsonFormat_Long
        {
            get => global::Google_PB.Protobuf_PB.FeatureSet_PB.JsonFormat_String.ToLong(jsonFormat);
            set => jsonFormat = global::Google_PB.Protobuf_PB.FeatureSet_PB.JsonFormat_String.FromLong(value);
        }
        
    }

}