// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.FieldDescriptorProto(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB {

    public class FieldDescriptorProto {
    
        public string name;
        
        public long number;
        
        public string label;
        public global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Label label_Enum
        {
            get => global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Label_String.ToEnum(label);
            set => label = global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Label_String.FromEnum(value);
        }
        public long label_Long
        {
            get => global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Label_String.ToLong(label);
            set => label = global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Label_String.FromLong(value);
        }
        
        public string type;
        public global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type type_Enum
        {
            get => global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type_String.ToEnum(type);
            set => type = global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type_String.FromEnum(value);
        }
        public long type_Long
        {
            get => global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type_String.ToLong(type);
            set => type = global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type_String.FromLong(value);
        }
        
        public string typeName;
        
        public string extendee;
        
        public string defaultValue;
        
        public long oneofIndex;
        
        public string jsonName;
        
        public global::Google_PB.Protobuf_PB.FieldOptions options;
        
        public bool proto3Optional;
        
    }

}