// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.FileOptions(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB {

    public class FileOptions {
    
        public string javaPackage;
        
        public string javaOuterClassname;
        
        public bool javaMultipleFiles;
        
        public bool javaGenerateEqualsAndHash;
        
        public bool javaStringCheckUtf8;
        
        public string optimizeFor;
        public global::Google_PB.Protobuf_PB.FileOptions_PB.OptimizeMode optimizeFor_Enum
        {
            get => global::Google_PB.Protobuf_PB.FileOptions_PB.OptimizeMode_String.ToEnum(optimizeFor);
            set => optimizeFor = global::Google_PB.Protobuf_PB.FileOptions_PB.OptimizeMode_String.FromEnum(value);
        }
        public long optimizeFor_Long
        {
            get => global::Google_PB.Protobuf_PB.FileOptions_PB.OptimizeMode_String.ToLong(optimizeFor);
            set => optimizeFor = global::Google_PB.Protobuf_PB.FileOptions_PB.OptimizeMode_String.FromLong(value);
        }
        
        public string goPackage;
        
        public bool ccGenericServices;
        
        public bool javaGenericServices;
        
        public bool pyGenericServices;
        
        public bool deprecated;
        
        public bool ccEnableArenas;
        
        public string objcClassPrefix;
        
        public string csharpNamespace;
        
        public string swiftPrefix;
        
        public string phpClassPrefix;
        
        public string phpNamespace;
        
        public string phpMetadataNamespace;
        
        public string rubyPackage;
        
        public global::Google_PB.Protobuf_PB.FeatureSet features;
        
        public global::System.Collections.Generic.List<global::Google_PB.Protobuf_PB.UninterpretedOption> uninterpretedOption;
        
    }

}