// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.FileDescriptorSet(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB {

    public class FileDescriptorSet {
    
        public global::System.Collections.Generic.List<global::Google_PB.Protobuf_PB.FileDescriptorProto> file;
        
    }

}