// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.FileDescriptorProto(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB {

    [System.Serializable]
    public class FileDescriptorProto {
    
        public string name;
        
        public string package;
        
        public global::System.Collections.Generic.List<string> dependency;
        
        public global::System.Collections.Generic.List<long> publicDependency;
        
        public global::System.Collections.Generic.List<long> weakDependency;
        
        public global::System.Collections.Generic.List<global::Google_PB.Protobuf_PB.DescriptorProto> messageType;
        
        public global::System.Collections.Generic.List<global::Google_PB.Protobuf_PB.EnumDescriptorProto> enumType;
        
        public global::System.Collections.Generic.List<global::Google_PB.Protobuf_PB.ServiceDescriptorProto> service;
        
        public global::System.Collections.Generic.List<global::Google_PB.Protobuf_PB.FieldDescriptorProto> extension;
        
        public global::Google_PB.Protobuf_PB.FileOptions options;
        
        public global::Google_PB.Protobuf_PB.SourceCodeInfo sourceCodeInfo;
        
        public string syntax;
        
        public string edition;
        public global::Google_PB.Protobuf_PB.Edition edition_Enum
        {
            get => global::Google_PB.Protobuf_PB.Edition_String.ToEnum(edition);
            set => edition = global::Google_PB.Protobuf_PB.Edition_String.FromEnum(value);
        }
        public long edition_Long
        {
            get => global::Google_PB.Protobuf_PB.Edition_String.ToLong(edition);
            set => edition = global::Google_PB.Protobuf_PB.Edition_String.FromLong(value);
        }
        
    }

}