// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.GeneratedCodeInfo(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB {

    public class GeneratedCodeInfo {
    
        public global::System.Collections.Generic.List<global::Google_PB.Protobuf_PB.GeneratedCodeInfo_PB.Annotation> annotation;
        
    }

}