// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.MessageOptions(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB {

    public class MessageOptions {
    
        public bool messageSetWireFormat;
        
        public bool noStandardDescriptorAccessor;
        
        public bool deprecated;
        
        public bool mapEntry;
        
        public bool deprecatedLegacyJsonFieldConflicts;
        
        public global::Google_PB.Protobuf_PB.FeatureSet features;
        
        public global::System.Collections.Generic.List<global::Google_PB.Protobuf_PB.UninterpretedOption> uninterpretedOption;
        
    }

}