// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.MethodDescriptorProto(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB {

    public class MethodDescriptorProto {
    
        public string name;
        
        public string inputType;
        
        public string outputType;
        
        public global::Google_PB.Protobuf_PB.MethodOptions options;
        
        public bool clientStreaming;
        
        public bool serverStreaming;
        
    }

}