// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.MethodOptions(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB {

    public class MethodOptions {
    
        public bool deprecated;
        
        public string idempotencyLevel;
        public global::Google_PB.Protobuf_PB.MethodOptions_PB.IdempotencyLevel idempotencyLevel_Enum
        {
            get => global::Google_PB.Protobuf_PB.MethodOptions_PB.IdempotencyLevel_String.ToEnum(idempotencyLevel);
            set => idempotencyLevel = global::Google_PB.Protobuf_PB.MethodOptions_PB.IdempotencyLevel_String.FromEnum(value);
        }
        public long idempotencyLevel_Long
        {
            get => global::Google_PB.Protobuf_PB.MethodOptions_PB.IdempotencyLevel_String.ToLong(idempotencyLevel);
            set => idempotencyLevel = global::Google_PB.Protobuf_PB.MethodOptions_PB.IdempotencyLevel_String.FromLong(value);
        }
        
        public global::Google_PB.Protobuf_PB.FeatureSet features;
        
        public global::System.Collections.Generic.List<global::Google_PB.Protobuf_PB.UninterpretedOption> uninterpretedOption;
        
    }

}