// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.OneofDescriptorProto(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB {

    [System.Serializable]
    public class OneofDescriptorProto {
    
        public string name;
        
        public global::Google_PB.Protobuf_PB.OneofOptions options;
        
    }

}