// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.OneofOptions(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB {

    public class OneofOptions {
    
        public global::Google_PB.Protobuf_PB.FeatureSet features;
        
        public global::System.Collections.Generic.List<global::Google_PB.Protobuf_PB.UninterpretedOption> uninterpretedOption;
        
    }

}