// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.ServiceDescriptorProto(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB {

    [System.Serializable]
    public class ServiceDescriptorProto {
    
        public string name;
        
        public global::System.Collections.Generic.List<global::Google_PB.Protobuf_PB.MethodDescriptorProto> method;
        
        public global::Google_PB.Protobuf_PB.ServiceOptions options;
        
    }

}