// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.SourceCodeInfo(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB {

    [System.Serializable]
    public class SourceCodeInfo {
    
        public global::System.Collections.Generic.List<global::Google_PB.Protobuf_PB.SourceCodeInfo_PB.Location> location;
        
    }

}