// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.Timestamp(google/protobuf/timestamp.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB {

    public class Timestamp {
    
        public long seconds;
        
        public long nanos;
        
    }

}