// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.UninterpretedOption(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB {

    [System.Serializable]
    public class UninterpretedOption {
    
        public global::System.Collections.Generic.List<global::Google_PB.Protobuf_PB.UninterpretedOption_PB.NamePart> name;
        
        public string identifierValue;
        
        public ulong positiveIntValue;
        
        public long negativeIntValue;
        
        public double doubleValue;
        
        public string stringValue;
        
        public string aggregateValue;
        
    }

}