// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: localdata.LocalData.Authentication(localdata/localdata.proto)
// </auto-generated>

namespace Localdata_PB.LocalData_PB {

    [System.Serializable]
    public class Authentication {
    
        public string accessToken;
        
        public string refreshToken;
        
    }

}