// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.FieldDescriptorProto.Label(google/protobuf/descriptor.proto)
// </auto-generated>



namespace Google_PB.Protobuf_PB.FieldDescriptorProto_PB {

    public enum Label {
    
        LabelOptional = 1,
    
        LabelRepeated = 3,
    
        LabelRequired = 2,
    
    }
    public class Label_String {
        public static string FromEnum(global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Label enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Label.LabelOptional:
                    return "LABEL_OPTIONAL";
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Label.LabelRepeated:
                    return "LABEL_REPEATED";
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Label.LabelRequired:
                    return "LABEL_REQUIRED";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static string FromLong(long longValue) {
            switch (longValue) {
            
                case 1:
                    return "LABEL_OPTIONAL";
            
                case 3:
                    return "LABEL_REPEATED";
            
                case 2:
                    return "LABEL_REQUIRED";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Label ToEnum(string stringValue) {
            switch (stringValue) {
            
                case "LABEL_OPTIONAL":
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Label.LabelOptional;
            
                case "LABEL_REPEATED":
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Label.LabelRepeated;
            
                case "LABEL_REQUIRED":
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Label.LabelRequired;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static long ToLong(string stringValue) {
            switch (stringValue) {
            
                case "LABEL_OPTIONAL":
                    return 1;
            
                case "LABEL_REPEATED":
                    return 3;
            
                case "LABEL_REQUIRED":
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
    
        public const string LabelOptional = "LABEL_OPTIONAL";
    
        public const string LabelRepeated = "LABEL_REPEATED";
    
        public const string LabelRequired = "LABEL_REQUIRED";
    
    }

    public class Label_Long {
        public static long FromEnum(global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Label enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Label.LabelOptional:
                    return 1;
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Label.LabelRepeated:
                    return 3;
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Label.LabelRequired:
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static long FromString(string stringValue) {
            switch (stringValue) {
            
                case "LABEL_OPTIONAL":
                    return 1;
            
                case "LABEL_REPEATED":
                    return 3;
            
                case "LABEL_REQUIRED":
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Label ToEnum(long longValue) {
            switch (longValue) {
            
                case 1:
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Label.LabelOptional;
            
                case 3:
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Label.LabelRepeated;
            
                case 2:
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Label.LabelRequired;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static string ToString(long longValue) {
            switch (longValue) {
            
                case 1:
                    return "LABEL_OPTIONAL";
            
                case 3:
                    return "LABEL_REPEATED";
            
                case 2:
                    return "LABEL_REQUIRED";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
    
        public const long LabelOptional = 1;
    
        public const long LabelRepeated = 3;
    
        public const long LabelRequired = 2;
    
    }
}