// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.app.room.play.GetHistoryResponse(api/v1/app/room/play/service.proto)
// </auto-generated>

namespace Api_PB.V1_PB.App_PB.Room_PB.Play_PB {

    public class GetHistoryResponse {
    
        public global::System.Collections.Generic.List<global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.GetHistoryResponse_PB.HistoryEntry> history;
        
    }

}