// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.app.room.play.Place(api/v1/app/room/play/service.proto)
// </auto-generated>

namespace Api_PB.V1_PB.App_PB.Room_PB.Play_PB {

    [System.Serializable]
    public class Place {
    
        public string placeId;
        
        public bool owned;
        
        public string ownerSeatId;
        
        public string type;
        public global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Place_PB.Type type_Enum
        {
            get => global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Place_PB.Type_String.ToEnum(type);
            set => type = global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Place_PB.Type_String.FromEnum(value);
        }
        public long type_Long
        {
            get => global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Place_PB.Type_String.ToLong(type);
            set => type = global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Place_PB.Type_String.FromLong(value);
        }
        
        public global::System.Collections.Generic.List<global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card> cardList;
        
    }

}