// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.FeatureSet.EnumType(google/protobuf/descriptor.proto)
// </auto-generated>



namespace Google_PB.Protobuf_PB.FeatureSet_PB {

    public enum EnumType {
    
        EnumTypeUnknown = 0,
    
        Open = 1,
    
        Closed = 2,
    
    }
    public class EnumType_String {
        public static string FromEnum(global::Google_PB.Protobuf_PB.FeatureSet_PB.EnumType enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.EnumType.EnumTypeUnknown:
                    return "ENUM_TYPE_UNKNOWN";
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.EnumType.Open:
                    return "OPEN";
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.EnumType.Closed:
                    return "CLOSED";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static string FromLong(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "ENUM_TYPE_UNKNOWN";
            
                case 1:
                    return "OPEN";
            
                case 2:
                    return "CLOSED";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.FeatureSet_PB.EnumType ToEnum(string stringValue) {
            switch (stringValue) {
            
                case "ENUM_TYPE_UNKNOWN":
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.EnumType.EnumTypeUnknown;
            
                case "OPEN":
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.EnumType.Open;
            
                case "CLOSED":
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.EnumType.Closed;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static long ToLong(string stringValue) {
            switch (stringValue) {
            
                case "ENUM_TYPE_UNKNOWN":
                    return 0;
            
                case "OPEN":
                    return 1;
            
                case "CLOSED":
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
    
        public const string EnumTypeUnknown = "ENUM_TYPE_UNKNOWN";
    
        public const string Open = "OPEN";
    
        public const string Closed = "CLOSED";
    
    }

    public class EnumType_Long {
        public static long FromEnum(global::Google_PB.Protobuf_PB.FeatureSet_PB.EnumType enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.EnumType.EnumTypeUnknown:
                    return 0;
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.EnumType.Open:
                    return 1;
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.EnumType.Closed:
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static long FromString(string stringValue) {
            switch (stringValue) {
            
                case "ENUM_TYPE_UNKNOWN":
                    return 0;
            
                case "OPEN":
                    return 1;
            
                case "CLOSED":
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.FeatureSet_PB.EnumType ToEnum(long longValue) {
            switch (longValue) {
            
                case 0:
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.EnumType.EnumTypeUnknown;
            
                case 1:
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.EnumType.Open;
            
                case 2:
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.EnumType.Closed;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static string ToString(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "ENUM_TYPE_UNKNOWN";
            
                case 1:
                    return "OPEN";
            
                case 2:
                    return "CLOSED";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
    
        public const long EnumTypeUnknown = 0;
    
        public const long Open = 1;
    
        public const long Closed = 2;
    
    }
}