// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.FeatureSet.RepeatedFieldEncoding(google/protobuf/descriptor.proto)
// </auto-generated>



namespace Google_PB.Protobuf_PB.FeatureSet_PB {

    public enum RepeatedFieldEncoding {
    
        RepeatedFieldEncodingUnknown = 0,
    
        Packed = 1,
    
        Expanded = 2,
    
    }
    public class RepeatedFieldEncoding_String {
        public static string FromEnum(global::Google_PB.Protobuf_PB.FeatureSet_PB.RepeatedFieldEncoding enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.RepeatedFieldEncoding.RepeatedFieldEncodingUnknown:
                    return "REPEATED_FIELD_ENCODING_UNKNOWN";
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.RepeatedFieldEncoding.Packed:
                    return "PACKED";
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.RepeatedFieldEncoding.Expanded:
                    return "EXPANDED";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static string FromLong(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "REPEATED_FIELD_ENCODING_UNKNOWN";
            
                case 1:
                    return "PACKED";
            
                case 2:
                    return "EXPANDED";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.FeatureSet_PB.RepeatedFieldEncoding ToEnum(string stringValue) {
            switch (stringValue) {
            
                case "REPEATED_FIELD_ENCODING_UNKNOWN":
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.RepeatedFieldEncoding.RepeatedFieldEncodingUnknown;
            
                case "PACKED":
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.RepeatedFieldEncoding.Packed;
            
                case "EXPANDED":
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.RepeatedFieldEncoding.Expanded;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static long ToLong(string stringValue) {
            switch (stringValue) {
            
                case "REPEATED_FIELD_ENCODING_UNKNOWN":
                    return 0;
            
                case "PACKED":
                    return 1;
            
                case "EXPANDED":
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
    
        public const string RepeatedFieldEncodingUnknown = "REPEATED_FIELD_ENCODING_UNKNOWN";
    
        public const string Packed = "PACKED";
    
        public const string Expanded = "EXPANDED";
    
    }

    public class RepeatedFieldEncoding_Long {
        public static long FromEnum(global::Google_PB.Protobuf_PB.FeatureSet_PB.RepeatedFieldEncoding enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.RepeatedFieldEncoding.RepeatedFieldEncodingUnknown:
                    return 0;
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.RepeatedFieldEncoding.Packed:
                    return 1;
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.RepeatedFieldEncoding.Expanded:
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static long FromString(string stringValue) {
            switch (stringValue) {
            
                case "REPEATED_FIELD_ENCODING_UNKNOWN":
                    return 0;
            
                case "PACKED":
                    return 1;
            
                case "EXPANDED":
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.FeatureSet_PB.RepeatedFieldEncoding ToEnum(long longValue) {
            switch (longValue) {
            
                case 0:
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.RepeatedFieldEncoding.RepeatedFieldEncodingUnknown;
            
                case 1:
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.RepeatedFieldEncoding.Packed;
            
                case 2:
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.RepeatedFieldEncoding.Expanded;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static string ToString(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "REPEATED_FIELD_ENCODING_UNKNOWN";
            
                case 1:
                    return "PACKED";
            
                case 2:
                    return "EXPANDED";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
    
        public const long RepeatedFieldEncodingUnknown = 0;
    
        public const long Packed = 1;
    
        public const long Expanded = 2;
    
    }
}