// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.FeatureSet.Utf8Validation(google/protobuf/descriptor.proto)
// </auto-generated>



namespace Google_PB.Protobuf_PB.FeatureSet_PB {

    public enum Utf8Validation {
    
        Utf8ValidationUnknown = 0,
    
        Verify = 2,
    
        None = 3,
    
    }
    public class Utf8Validation_String {
        public static string FromEnum(global::Google_PB.Protobuf_PB.FeatureSet_PB.Utf8Validation enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.Utf8Validation.Utf8ValidationUnknown:
                    return "UTF8_VALIDATION_UNKNOWN";
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.Utf8Validation.Verify:
                    return "VERIFY";
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.Utf8Validation.None:
                    return "NONE";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static string FromLong(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "UTF8_VALIDATION_UNKNOWN";
            
                case 2:
                    return "VERIFY";
            
                case 3:
                    return "NONE";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.FeatureSet_PB.Utf8Validation ToEnum(string stringValue) {
            switch (stringValue) {
            
                case "UTF8_VALIDATION_UNKNOWN":
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.Utf8Validation.Utf8ValidationUnknown;
            
                case "VERIFY":
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.Utf8Validation.Verify;
            
                case "NONE":
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.Utf8Validation.None;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static long ToLong(string stringValue) {
            switch (stringValue) {
            
                case "UTF8_VALIDATION_UNKNOWN":
                    return 0;
            
                case "VERIFY":
                    return 2;
            
                case "NONE":
                    return 3;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
    
        public const string Utf8ValidationUnknown = "UTF8_VALIDATION_UNKNOWN";
    
        public const string Verify = "VERIFY";
    
        public const string None = "NONE";
    
    }

    public class Utf8Validation_Long {
        public static long FromEnum(global::Google_PB.Protobuf_PB.FeatureSet_PB.Utf8Validation enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.Utf8Validation.Utf8ValidationUnknown:
                    return 0;
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.Utf8Validation.Verify:
                    return 2;
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.Utf8Validation.None:
                    return 3;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static long FromString(string stringValue) {
            switch (stringValue) {
            
                case "UTF8_VALIDATION_UNKNOWN":
                    return 0;
            
                case "VERIFY":
                    return 2;
            
                case "NONE":
                    return 3;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.FeatureSet_PB.Utf8Validation ToEnum(long longValue) {
            switch (longValue) {
            
                case 0:
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.Utf8Validation.Utf8ValidationUnknown;
            
                case 2:
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.Utf8Validation.Verify;
            
                case 3:
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.Utf8Validation.None;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static string ToString(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "UTF8_VALIDATION_UNKNOWN";
            
                case 2:
                    return "VERIFY";
            
                case 3:
                    return "NONE";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
    
        public const long Utf8ValidationUnknown = 0;
    
        public const long Verify = 2;
    
        public const long None = 3;
    
    }
}