// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.EnumDescriptorProto.EnumReservedRange(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB.EnumDescriptorProto_PB {

    [System.Serializable]
    public class EnumReservedRange {
    
        public long start;
        
        public long end;
        
    }

}