// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.app.room.GetResponse(api/v1/app/room/service.proto)
// </auto-generated>

namespace Api_PB.V1_PB.App_PB.Room_PB {

    public class GetResponse {
    
        public string roomId;
        
        public string roomName;
        
        public global::System.Collections.Generic.List<global::Api_PB.V1_PB.App_PB.Room_PB.RoomSeat> seatList;
        
        public global::System.Collections.Generic.List<global::Api_PB.V1_PB.App_PB.Room_PB.RoomMember> memberList;
        
    }

}