// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.app.room.LeaveSeatResponse(api/v1/app/room/service.proto)
// </auto-generated>

namespace Api_PB.V1_PB.App_PB.Room_PB {

    [System.Serializable]
    public class LeaveSeatResponse {
    
    }

}