// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.app.room.RoomMember(api/v1/app/room/service.proto)
// </auto-generated>

namespace Api_PB.V1_PB.App_PB.Room_PB {

    public class RoomMember {
    
        public string memberId;
        
        public string memberRole;
        
        public string userId;
        
        public string userName;
        
    }

}