// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.app.room.play.Card.Rank(api/v1/app/room/play/service.proto)
// </auto-generated>



namespace Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB {

    public enum Rank {
    
        RankUnspecified = 0,
    
        RankAce = 1,
    
        Rank2 = 2,
    
        Rank3 = 3,
    
        Rank4 = 4,
    
        Rank5 = 5,
    
        Rank6 = 6,
    
        Rank7 = 7,
    
        Rank8 = 8,
    
        Rank9 = 9,
    
        Rank10 = 10,
    
        RankJack = 11,
    
        RankQueen = 12,
    
        RankKing = 13,
    
        RankJoker = 14,
    
    }
    public class Rank_String {
        public static string FromEnum(global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank enumValue) {
            switch (enumValue) {
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.RankUnspecified:
                    return "RANK_UNSPECIFIED";
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.RankAce:
                    return "RANK_ACE";
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank2:
                    return "RANK_2";
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank3:
                    return "RANK_3";
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank4:
                    return "RANK_4";
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank5:
                    return "RANK_5";
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank6:
                    return "RANK_6";
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank7:
                    return "RANK_7";
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank8:
                    return "RANK_8";
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank9:
                    return "RANK_9";
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank10:
                    return "RANK_10";
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.RankJack:
                    return "RANK_JACK";
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.RankQueen:
                    return "RANK_QUEEN";
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.RankKing:
                    return "RANK_KING";
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.RankJoker:
                    return "RANK_JOKER";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static string FromLong(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "RANK_UNSPECIFIED";
            
                case 1:
                    return "RANK_ACE";
            
                case 2:
                    return "RANK_2";
            
                case 3:
                    return "RANK_3";
            
                case 4:
                    return "RANK_4";
            
                case 5:
                    return "RANK_5";
            
                case 6:
                    return "RANK_6";
            
                case 7:
                    return "RANK_7";
            
                case 8:
                    return "RANK_8";
            
                case 9:
                    return "RANK_9";
            
                case 10:
                    return "RANK_10";
            
                case 11:
                    return "RANK_JACK";
            
                case 12:
                    return "RANK_QUEEN";
            
                case 13:
                    return "RANK_KING";
            
                case 14:
                    return "RANK_JOKER";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank ToEnum(string stringValue) {
            switch (stringValue) {
            
                case "RANK_UNSPECIFIED":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.RankUnspecified;
            
                case "RANK_ACE":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.RankAce;
            
                case "RANK_2":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank2;
            
                case "RANK_3":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank3;
            
                case "RANK_4":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank4;
            
                case "RANK_5":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank5;
            
                case "RANK_6":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank6;
            
                case "RANK_7":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank7;
            
                case "RANK_8":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank8;
            
                case "RANK_9":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank9;
            
                case "RANK_10":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank10;
            
                case "RANK_JACK":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.RankJack;
            
                case "RANK_QUEEN":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.RankQueen;
            
                case "RANK_KING":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.RankKing;
            
                case "RANK_JOKER":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.RankJoker;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static long ToLong(string stringValue) {
            switch (stringValue) {
            
                case "RANK_UNSPECIFIED":
                    return 0;
            
                case "RANK_ACE":
                    return 1;
            
                case "RANK_2":
                    return 2;
            
                case "RANK_3":
                    return 3;
            
                case "RANK_4":
                    return 4;
            
                case "RANK_5":
                    return 5;
            
                case "RANK_6":
                    return 6;
            
                case "RANK_7":
                    return 7;
            
                case "RANK_8":
                    return 8;
            
                case "RANK_9":
                    return 9;
            
                case "RANK_10":
                    return 10;
            
                case "RANK_JACK":
                    return 11;
            
                case "RANK_QUEEN":
                    return 12;
            
                case "RANK_KING":
                    return 13;
            
                case "RANK_JOKER":
                    return 14;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
    
        public const string RankUnspecified = "RANK_UNSPECIFIED";
    
        public const string RankAce = "RANK_ACE";
    
        public const string Rank2 = "RANK_2";
    
        public const string Rank3 = "RANK_3";
    
        public const string Rank4 = "RANK_4";
    
        public const string Rank5 = "RANK_5";
    
        public const string Rank6 = "RANK_6";
    
        public const string Rank7 = "RANK_7";
    
        public const string Rank8 = "RANK_8";
    
        public const string Rank9 = "RANK_9";
    
        public const string Rank10 = "RANK_10";
    
        public const string RankJack = "RANK_JACK";
    
        public const string RankQueen = "RANK_QUEEN";
    
        public const string RankKing = "RANK_KING";
    
        public const string RankJoker = "RANK_JOKER";
    
    }

    public class Rank_Long {
        public static long FromEnum(global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank enumValue) {
            switch (enumValue) {
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.RankUnspecified:
                    return 0;
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.RankAce:
                    return 1;
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank2:
                    return 2;
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank3:
                    return 3;
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank4:
                    return 4;
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank5:
                    return 5;
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank6:
                    return 6;
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank7:
                    return 7;
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank8:
                    return 8;
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank9:
                    return 9;
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank10:
                    return 10;
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.RankJack:
                    return 11;
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.RankQueen:
                    return 12;
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.RankKing:
                    return 13;
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.RankJoker:
                    return 14;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static long FromString(string stringValue) {
            switch (stringValue) {
            
                case "RANK_UNSPECIFIED":
                    return 0;
            
                case "RANK_ACE":
                    return 1;
            
                case "RANK_2":
                    return 2;
            
                case "RANK_3":
                    return 3;
            
                case "RANK_4":
                    return 4;
            
                case "RANK_5":
                    return 5;
            
                case "RANK_6":
                    return 6;
            
                case "RANK_7":
                    return 7;
            
                case "RANK_8":
                    return 8;
            
                case "RANK_9":
                    return 9;
            
                case "RANK_10":
                    return 10;
            
                case "RANK_JACK":
                    return 11;
            
                case "RANK_QUEEN":
                    return 12;
            
                case "RANK_KING":
                    return 13;
            
                case "RANK_JOKER":
                    return 14;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank ToEnum(long longValue) {
            switch (longValue) {
            
                case 0:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.RankUnspecified;
            
                case 1:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.RankAce;
            
                case 2:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank2;
            
                case 3:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank3;
            
                case 4:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank4;
            
                case 5:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank5;
            
                case 6:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank6;
            
                case 7:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank7;
            
                case 8:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank8;
            
                case 9:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank9;
            
                case 10:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.Rank10;
            
                case 11:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.RankJack;
            
                case 12:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.RankQueen;
            
                case 13:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.RankKing;
            
                case 14:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Rank.RankJoker;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static string ToString(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "RANK_UNSPECIFIED";
            
                case 1:
                    return "RANK_ACE";
            
                case 2:
                    return "RANK_2";
            
                case 3:
                    return "RANK_3";
            
                case 4:
                    return "RANK_4";
            
                case 5:
                    return "RANK_5";
            
                case 6:
                    return "RANK_6";
            
                case 7:
                    return "RANK_7";
            
                case 8:
                    return "RANK_8";
            
                case 9:
                    return "RANK_9";
            
                case 10:
                    return "RANK_10";
            
                case 11:
                    return "RANK_JACK";
            
                case 12:
                    return "RANK_QUEEN";
            
                case 13:
                    return "RANK_KING";
            
                case 14:
                    return "RANK_JOKER";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
    
        public const long RankUnspecified = 0;
    
        public const long RankAce = 1;
    
        public const long Rank2 = 2;
    
        public const long Rank3 = 3;
    
        public const long Rank4 = 4;
    
        public const long Rank5 = 5;
    
        public const long Rank6 = 6;
    
        public const long Rank7 = 7;
    
        public const long Rank8 = 8;
    
        public const long Rank9 = 9;
    
        public const long Rank10 = 10;
    
        public const long RankJack = 11;
    
        public const long RankQueen = 12;
    
        public const long RankKing = 13;
    
        public const long RankJoker = 14;
    
    }
}