// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.app.room.play.Card.Side(api/v1/app/room/play/service.proto)
// </auto-generated>



namespace Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB {

    public enum Side {
    
        SideUnspecified = 0,
    
        SideBack = 1,
    
        SideFront = 2,
    
    }
    public class Side_String {
        public static string FromEnum(global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side enumValue) {
            switch (enumValue) {
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side.SideUnspecified:
                    return "SIDE_UNSPECIFIED";
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side.SideBack:
                    return "SIDE_BACK";
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side.SideFront:
                    return "SIDE_FRONT";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static string FromLong(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "SIDE_UNSPECIFIED";
            
                case 1:
                    return "SIDE_BACK";
            
                case 2:
                    return "SIDE_FRONT";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side ToEnum(string stringValue) {
            switch (stringValue) {
            
                case "SIDE_UNSPECIFIED":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side.SideUnspecified;
            
                case "SIDE_BACK":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side.SideBack;
            
                case "SIDE_FRONT":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side.SideFront;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static long ToLong(string stringValue) {
            switch (stringValue) {
            
                case "SIDE_UNSPECIFIED":
                    return 0;
            
                case "SIDE_BACK":
                    return 1;
            
                case "SIDE_FRONT":
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
    
        public const string SideUnspecified = "SIDE_UNSPECIFIED";
    
        public const string SideBack = "SIDE_BACK";
    
        public const string SideFront = "SIDE_FRONT";
    
    }

    public class Side_Long {
        public static long FromEnum(global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side enumValue) {
            switch (enumValue) {
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side.SideUnspecified:
                    return 0;
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side.SideBack:
                    return 1;
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side.SideFront:
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static long FromString(string stringValue) {
            switch (stringValue) {
            
                case "SIDE_UNSPECIFIED":
                    return 0;
            
                case "SIDE_BACK":
                    return 1;
            
                case "SIDE_FRONT":
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side ToEnum(long longValue) {
            switch (longValue) {
            
                case 0:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side.SideUnspecified;
            
                case 1:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side.SideBack;
            
                case 2:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side.SideFront;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static string ToString(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "SIDE_UNSPECIFIED";
            
                case 1:
                    return "SIDE_BACK";
            
                case 2:
                    return "SIDE_FRONT";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
    
        public const long SideUnspecified = 0;
    
        public const long SideBack = 1;
    
        public const long SideFront = 2;
    
    }
}