// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.app.room.play.GetHistoryResponse.HistoryEntry(api/v1/app/room/play/service.proto)
// </auto-generated>

namespace Api_PB.V1_PB.App_PB.Room_PB.Play_PB.GetHistoryResponse_PB {

    [System.Serializable]
    public class HistoryEntry {
    
        public string historyEntryOrder;
        
        public string timestamp;
        public global::System.DateTime timestamp_DateTime
        {
            get => global::System.DateTime.Parse(timestamp);
            set => timestamp = value.ToString("o");
        }
        
        public string operatorSeatId;
        
        public string operatorMemberId;
        
        public string operation;
        public global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.GetHistoryResponse_PB.HistoryEntry_PB.Operation operation_Enum
        {
            get => global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.GetHistoryResponse_PB.HistoryEntry_PB.Operation_String.ToEnum(operation);
            set => operation = global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.GetHistoryResponse_PB.HistoryEntry_PB.Operation_String.FromEnum(value);
        }
        public long operation_Long
        {
            get => global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.GetHistoryResponse_PB.HistoryEntry_PB.Operation_String.ToLong(operation);
            set => operation = global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.GetHistoryResponse_PB.HistoryEntry_PB.Operation_String.FromLong(value);
        }
        
        public string placeId;
        
        public string sourceCardIndex;
        
        public string destinationPlaceId;
        
        public string destinationCardSide;
        public global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side destinationCardSide_Enum
        {
            get => global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side_String.ToEnum(destinationCardSide);
            set => destinationCardSide = global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side_String.FromEnum(value);
        }
        public long destinationCardSide_Long
        {
            get => global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side_String.ToLong(destinationCardSide);
            set => destinationCardSide = global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side_String.FromLong(value);
        }
        
    }

}