version: '3'

services:

  work:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
      - /workspace/backend/node_modules
    ports:
      - "3000:3000"
    working_dir: /workspace/backend
    tty: true
    command: [ "sleep", "infinity" ]

  postgres:
    image: postgres:17.2-alpine3.20
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=main
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    ports:
      - "8080:8080"