version: '3'

services:
  work:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
      - /workspace/backend/node_modules
    tty: true
    working_dir: /workspace/backend
    command: [ "sleep", "infinity" ]
    ports:
      - "3000:3000"
