version: '3'

services:
  work:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - /workspace/node_modules
    tty: true
    command: [ "sleep", "infinity" ]
    ports:
      - "3000:3000"
