// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.DescriptorProto.ExtensionRange(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB.DescriptorProto_PB {

    [System.Serializable]
    public class ExtensionRange {
    
        public long start;
        
        public long end;
        
        public global::Google_PB.Protobuf_PB.ExtensionRangeOptions options;
        
    }

}