// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.DescriptorProto.ReservedRange(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB.DescriptorProto_PB {

    public class ReservedRange {
    
        public long start;
        
        public long end;
        
    }

}