// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.ExtensionRangeOptions.Declaration(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB.ExtensionRangeOptions_PB {

    public class Declaration {
    
        public long number;
        
        public string fullName;
        
        public string type;
        
        public bool reserved;
        
        public bool repeated;
        
    }

}