// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.ExtensionRangeOptions.VerificationState(google/protobuf/descriptor.proto)
// </auto-generated>



namespace Google_PB.Protobuf_PB.ExtensionRangeOptions_PB {

    public enum VerificationState {
    
        Declaration = 0,
    
        Unverified = 1,
    
    }
    public class VerificationState_String {
        public static string FromEnum(global::Google_PB.Protobuf_PB.ExtensionRangeOptions_PB.VerificationState enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.ExtensionRangeOptions_PB.VerificationState.Declaration:
                    return "DECLARATION";
            
                case global::Google_PB.Protobuf_PB.ExtensionRangeOptions_PB.VerificationState.Unverified:
                    return "UNVERIFIED";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static string FromLong(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "DECLARATION";
            
                case 1:
                    return "UNVERIFIED";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.ExtensionRangeOptions_PB.VerificationState ToEnum(string stringValue) {
            switch (stringValue) {
            
                case "DECLARATION":
                    return global::Google_PB.Protobuf_PB.ExtensionRangeOptions_PB.VerificationState.Declaration;
            
                case "UNVERIFIED":
                    return global::Google_PB.Protobuf_PB.ExtensionRangeOptions_PB.VerificationState.Unverified;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static long ToLong(string stringValue) {
            switch (stringValue) {
            
                case "DECLARATION":
                    return 0;
            
                case "UNVERIFIED":
                    return 1;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
    
        public const string Declaration = "DECLARATION";
    
        public const string Unverified = "UNVERIFIED";
    
    }

    public class VerificationState_Long {
        public static long FromEnum(global::Google_PB.Protobuf_PB.ExtensionRangeOptions_PB.VerificationState enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.ExtensionRangeOptions_PB.VerificationState.Declaration:
                    return 0;
            
                case global::Google_PB.Protobuf_PB.ExtensionRangeOptions_PB.VerificationState.Unverified:
                    return 1;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static long FromString(string stringValue) {
            switch (stringValue) {
            
                case "DECLARATION":
                    return 0;
            
                case "UNVERIFIED":
                    return 1;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.ExtensionRangeOptions_PB.VerificationState ToEnum(long longValue) {
            switch (longValue) {
            
                case 0:
                    return global::Google_PB.Protobuf_PB.ExtensionRangeOptions_PB.VerificationState.Declaration;
            
                case 1:
                    return global::Google_PB.Protobuf_PB.ExtensionRangeOptions_PB.VerificationState.Unverified;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static string ToString(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "DECLARATION";
            
                case 1:
                    return "UNVERIFIED";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
    
        public const long Declaration = 0;
    
        public const long Unverified = 1;
    
    }
}