// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.SourceCodeInfo.Location(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB.SourceCodeInfo_PB {

    public class Location {
    
        public global::System.Collections.Generic.List<long> path;
        
        public global::System.Collections.Generic.List<long> span;
        
        public string leadingComments;
        
        public string trailingComments;
        
        public global::System.Collections.Generic.List<string> leadingDetachedComments;
        
    }

}