// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.Edition(google/protobuf/descriptor.proto)
// </auto-generated>



namespace Google_PB.Protobuf_PB {

    public enum Edition {
    
        EditionUnknown = 0,
    
        EditionLegacy = 900,
    
        EditionProto2 = 998,
    
        EditionProto3 = 999,
    
        Edition2023 = 1000,
    
        Edition2024 = 1001,
    
        Edition1TestOnly = 1,
    
        Edition2TestOnly = 2,
    
        Edition99997TestOnly = 99997,
    
        Edition99998TestOnly = 99998,
    
        Edition99999TestOnly = 99999,
    
        EditionMax = 2147483647,
    
    }
    public class Edition_String {
        public static string FromEnum(global::Google_PB.Protobuf_PB.Edition enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.Edition.EditionUnknown:
                    return "EDITION_UNKNOWN";
            
                case global::Google_PB.Protobuf_PB.Edition.EditionLegacy:
                    return "EDITION_LEGACY";
            
                case global::Google_PB.Protobuf_PB.Edition.EditionProto2:
                    return "EDITION_PROTO2";
            
                case global::Google_PB.Protobuf_PB.Edition.EditionProto3:
                    return "EDITION_PROTO3";
            
                case global::Google_PB.Protobuf_PB.Edition.Edition2023:
                    return "EDITION_2023";
            
                case global::Google_PB.Protobuf_PB.Edition.Edition2024:
                    return "EDITION_2024";
            
                case global::Google_PB.Protobuf_PB.Edition.Edition1TestOnly:
                    return "EDITION_1_TEST_ONLY";
            
                case global::Google_PB.Protobuf_PB.Edition.Edition2TestOnly:
                    return "EDITION_2_TEST_ONLY";
            
                case global::Google_PB.Protobuf_PB.Edition.Edition99997TestOnly:
                    return "EDITION_99997_TEST_ONLY";
            
                case global::Google_PB.Protobuf_PB.Edition.Edition99998TestOnly:
                    return "EDITION_99998_TEST_ONLY";
            
                case global::Google_PB.Protobuf_PB.Edition.Edition99999TestOnly:
                    return "EDITION_99999_TEST_ONLY";
            
                case global::Google_PB.Protobuf_PB.Edition.EditionMax:
                    return "EDITION_MAX";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static string FromLong(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "EDITION_UNKNOWN";
            
                case 900:
                    return "EDITION_LEGACY";
            
                case 998:
                    return "EDITION_PROTO2";
            
                case 999:
                    return "EDITION_PROTO3";
            
                case 1000:
                    return "EDITION_2023";
            
                case 1001:
                    return "EDITION_2024";
            
                case 1:
                    return "EDITION_1_TEST_ONLY";
            
                case 2:
                    return "EDITION_2_TEST_ONLY";
            
                case 99997:
                    return "EDITION_99997_TEST_ONLY";
            
                case 99998:
                    return "EDITION_99998_TEST_ONLY";
            
                case 99999:
                    return "EDITION_99999_TEST_ONLY";
            
                case 2147483647:
                    return "EDITION_MAX";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.Edition ToEnum(string stringValue) {
            switch (stringValue) {
            
                case "EDITION_UNKNOWN":
                    return global::Google_PB.Protobuf_PB.Edition.EditionUnknown;
            
                case "EDITION_LEGACY":
                    return global::Google_PB.Protobuf_PB.Edition.EditionLegacy;
            
                case "EDITION_PROTO2":
                    return global::Google_PB.Protobuf_PB.Edition.EditionProto2;
            
                case "EDITION_PROTO3":
                    return global::Google_PB.Protobuf_PB.Edition.EditionProto3;
            
                case "EDITION_2023":
                    return global::Google_PB.Protobuf_PB.Edition.Edition2023;
            
                case "EDITION_2024":
                    return global::Google_PB.Protobuf_PB.Edition.Edition2024;
            
                case "EDITION_1_TEST_ONLY":
                    return global::Google_PB.Protobuf_PB.Edition.Edition1TestOnly;
            
                case "EDITION_2_TEST_ONLY":
                    return global::Google_PB.Protobuf_PB.Edition.Edition2TestOnly;
            
                case "EDITION_99997_TEST_ONLY":
                    return global::Google_PB.Protobuf_PB.Edition.Edition99997TestOnly;
            
                case "EDITION_99998_TEST_ONLY":
                    return global::Google_PB.Protobuf_PB.Edition.Edition99998TestOnly;
            
                case "EDITION_99999_TEST_ONLY":
                    return global::Google_PB.Protobuf_PB.Edition.Edition99999TestOnly;
            
                case "EDITION_MAX":
                    return global::Google_PB.Protobuf_PB.Edition.EditionMax;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static long ToLong(string stringValue) {
            switch (stringValue) {
            
                case "EDITION_UNKNOWN":
                    return 0;
            
                case "EDITION_LEGACY":
                    return 900;
            
                case "EDITION_PROTO2":
                    return 998;
            
                case "EDITION_PROTO3":
                    return 999;
            
                case "EDITION_2023":
                    return 1000;
            
                case "EDITION_2024":
                    return 1001;
            
                case "EDITION_1_TEST_ONLY":
                    return 1;
            
                case "EDITION_2_TEST_ONLY":
                    return 2;
            
                case "EDITION_99997_TEST_ONLY":
                    return 99997;
            
                case "EDITION_99998_TEST_ONLY":
                    return 99998;
            
                case "EDITION_99999_TEST_ONLY":
                    return 99999;
            
                case "EDITION_MAX":
                    return 2147483647;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
    
        public const string EditionUnknown = "EDITION_UNKNOWN";
    
        public const string EditionLegacy = "EDITION_LEGACY";
    
        public const string EditionProto2 = "EDITION_PROTO2";
    
        public const string EditionProto3 = "EDITION_PROTO3";
    
        public const string Edition2023 = "EDITION_2023";
    
        public const string Edition2024 = "EDITION_2024";
    
        public const string Edition1TestOnly = "EDITION_1_TEST_ONLY";
    
        public const string Edition2TestOnly = "EDITION_2_TEST_ONLY";
    
        public const string Edition99997TestOnly = "EDITION_99997_TEST_ONLY";
    
        public const string Edition99998TestOnly = "EDITION_99998_TEST_ONLY";
    
        public const string Edition99999TestOnly = "EDITION_99999_TEST_ONLY";
    
        public const string EditionMax = "EDITION_MAX";
    
    }

    public class Edition_Long {
        public static long FromEnum(global::Google_PB.Protobuf_PB.Edition enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.Edition.EditionUnknown:
                    return 0;
            
                case global::Google_PB.Protobuf_PB.Edition.EditionLegacy:
                    return 900;
            
                case global::Google_PB.Protobuf_PB.Edition.EditionProto2:
                    return 998;
            
                case global::Google_PB.Protobuf_PB.Edition.EditionProto3:
                    return 999;
            
                case global::Google_PB.Protobuf_PB.Edition.Edition2023:
                    return 1000;
            
                case global::Google_PB.Protobuf_PB.Edition.Edition2024:
                    return 1001;
            
                case global::Google_PB.Protobuf_PB.Edition.Edition1TestOnly:
                    return 1;
            
                case global::Google_PB.Protobuf_PB.Edition.Edition2TestOnly:
                    return 2;
            
                case global::Google_PB.Protobuf_PB.Edition.Edition99997TestOnly:
                    return 99997;
            
                case global::Google_PB.Protobuf_PB.Edition.Edition99998TestOnly:
                    return 99998;
            
                case global::Google_PB.Protobuf_PB.Edition.Edition99999TestOnly:
                    return 99999;
            
                case global::Google_PB.Protobuf_PB.Edition.EditionMax:
                    return 2147483647;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static long FromString(string stringValue) {
            switch (stringValue) {
            
                case "EDITION_UNKNOWN":
                    return 0;
            
                case "EDITION_LEGACY":
                    return 900;
            
                case "EDITION_PROTO2":
                    return 998;
            
                case "EDITION_PROTO3":
                    return 999;
            
                case "EDITION_2023":
                    return 1000;
            
                case "EDITION_2024":
                    return 1001;
            
                case "EDITION_1_TEST_ONLY":
                    return 1;
            
                case "EDITION_2_TEST_ONLY":
                    return 2;
            
                case "EDITION_99997_TEST_ONLY":
                    return 99997;
            
                case "EDITION_99998_TEST_ONLY":
                    return 99998;
            
                case "EDITION_99999_TEST_ONLY":
                    return 99999;
            
                case "EDITION_MAX":
                    return 2147483647;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.Edition ToEnum(long longValue) {
            switch (longValue) {
            
                case 0:
                    return global::Google_PB.Protobuf_PB.Edition.EditionUnknown;
            
                case 900:
                    return global::Google_PB.Protobuf_PB.Edition.EditionLegacy;
            
                case 998:
                    return global::Google_PB.Protobuf_PB.Edition.EditionProto2;
            
                case 999:
                    return global::Google_PB.Protobuf_PB.Edition.EditionProto3;
            
                case 1000:
                    return global::Google_PB.Protobuf_PB.Edition.Edition2023;
            
                case 1001:
                    return global::Google_PB.Protobuf_PB.Edition.Edition2024;
            
                case 1:
                    return global::Google_PB.Protobuf_PB.Edition.Edition1TestOnly;
            
                case 2:
                    return global::Google_PB.Protobuf_PB.Edition.Edition2TestOnly;
            
                case 99997:
                    return global::Google_PB.Protobuf_PB.Edition.Edition99997TestOnly;
            
                case 99998:
                    return global::Google_PB.Protobuf_PB.Edition.Edition99998TestOnly;
            
                case 99999:
                    return global::Google_PB.Protobuf_PB.Edition.Edition99999TestOnly;
            
                case 2147483647:
                    return global::Google_PB.Protobuf_PB.Edition.EditionMax;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static string ToString(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "EDITION_UNKNOWN";
            
                case 900:
                    return "EDITION_LEGACY";
            
                case 998:
                    return "EDITION_PROTO2";
            
                case 999:
                    return "EDITION_PROTO3";
            
                case 1000:
                    return "EDITION_2023";
            
                case 1001:
                    return "EDITION_2024";
            
                case 1:
                    return "EDITION_1_TEST_ONLY";
            
                case 2:
                    return "EDITION_2_TEST_ONLY";
            
                case 99997:
                    return "EDITION_99997_TEST_ONLY";
            
                case 99998:
                    return "EDITION_99998_TEST_ONLY";
            
                case 99999:
                    return "EDITION_99999_TEST_ONLY";
            
                case 2147483647:
                    return "EDITION_MAX";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
    
        public const long EditionUnknown = 0;
    
        public const long EditionLegacy = 900;
    
        public const long EditionProto2 = 998;
    
        public const long EditionProto3 = 999;
    
        public const long Edition2023 = 1000;
    
        public const long Edition2024 = 1001;
    
        public const long Edition1TestOnly = 1;
    
        public const long Edition2TestOnly = 2;
    
        public const long Edition99997TestOnly = 99997;
    
        public const long Edition99998TestOnly = 99998;
    
        public const long Edition99999TestOnly = 99999;
    
        public const long EditionMax = 2147483647;
    
    }
}