// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.EnumValueDescriptorProto(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB {

    [System.Serializable]
    public class EnumValueDescriptorProto {
    
        public string name;
        
        public long number;
        
        public global::Google_PB.Protobuf_PB.EnumValueOptions options;
        
    }

}