// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.FieldOptions(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB {

    [System.Serializable]
    public class FieldOptions {
    
        public string ctype;
        public global::Google_PB.Protobuf_PB.FieldOptions_PB.Ctype ctype_Enum
        {
            get => global::Google_PB.Protobuf_PB.FieldOptions_PB.Ctype_String.ToEnum(ctype);
            set => ctype = global::Google_PB.Protobuf_PB.FieldOptions_PB.Ctype_String.FromEnum(value);
        }
        public long ctype_Long
        {
            get => global::Google_PB.Protobuf_PB.FieldOptions_PB.Ctype_String.ToLong(ctype);
            set => ctype = global::Google_PB.Protobuf_PB.FieldOptions_PB.Ctype_String.FromLong(value);
        }
        
        public bool packed;
        
        public string jstype;
        public global::Google_PB.Protobuf_PB.FieldOptions_PB.Jstype jstype_Enum
        {
            get => global::Google_PB.Protobuf_PB.FieldOptions_PB.Jstype_String.ToEnum(jstype);
            set => jstype = global::Google_PB.Protobuf_PB.FieldOptions_PB.Jstype_String.FromEnum(value);
        }
        public long jstype_Long
        {
            get => global::Google_PB.Protobuf_PB.FieldOptions_PB.Jstype_String.ToLong(jstype);
            set => jstype = global::Google_PB.Protobuf_PB.FieldOptions_PB.Jstype_String.FromLong(value);
        }
        
        public bool lazy;
        
        public bool unverifiedLazy;
        
        public bool deprecated;
        
        public bool weak;
        
        public bool debugRedact;
        
        public string retention;
        public global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionRetention retention_Enum
        {
            get => global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionRetention_String.ToEnum(retention);
            set => retention = global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionRetention_String.FromEnum(value);
        }
        public long retention_Long
        {
            get => global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionRetention_String.ToLong(retention);
            set => retention = global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionRetention_String.FromLong(value);
        }
        
        public global::System.Collections.Generic.List<string> targets;
        
        public global::System.Collections.Generic.List<global::Google_PB.Protobuf_PB.FieldOptions_PB.EditionDefault> editionDefaults;
        
        public global::Google_PB.Protobuf_PB.FeatureSet features;
        
        public global::Google_PB.Protobuf_PB.FieldOptions_PB.FeatureSupport featureSupport;
        
        public global::System.Collections.Generic.List<global::Google_PB.Protobuf_PB.UninterpretedOption> uninterpretedOption;
        
    }

}