// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.FieldOptions.CType(google/protobuf/descriptor.proto)
// </auto-generated>



namespace Google_PB.Protobuf_PB.FieldOptions_PB {

    public enum Ctype {
    
        String = 0,
    
        Cord = 1,
    
        StringPiece = 2,
    
    }
    public class Ctype_String {
        public static string FromEnum(global::Google_PB.Protobuf_PB.FieldOptions_PB.Ctype enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.Ctype.String:
                    return "STRING";
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.Ctype.Cord:
                    return "CORD";
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.Ctype.StringPiece:
                    return "STRING_PIECE";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static string FromLong(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "STRING";
            
                case 1:
                    return "CORD";
            
                case 2:
                    return "STRING_PIECE";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.FieldOptions_PB.Ctype ToEnum(string stringValue) {
            switch (stringValue) {
            
                case "STRING":
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.Ctype.String;
            
                case "CORD":
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.Ctype.Cord;
            
                case "STRING_PIECE":
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.Ctype.StringPiece;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static long ToLong(string stringValue) {
            switch (stringValue) {
            
                case "STRING":
                    return 0;
            
                case "CORD":
                    return 1;
            
                case "STRING_PIECE":
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
    
        public const string String = "STRING";
    
        public const string Cord = "CORD";
    
        public const string StringPiece = "STRING_PIECE";
    
    }

    public class Ctype_Long {
        public static long FromEnum(global::Google_PB.Protobuf_PB.FieldOptions_PB.Ctype enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.Ctype.String:
                    return 0;
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.Ctype.Cord:
                    return 1;
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.Ctype.StringPiece:
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static long FromString(string stringValue) {
            switch (stringValue) {
            
                case "STRING":
                    return 0;
            
                case "CORD":
                    return 1;
            
                case "STRING_PIECE":
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.FieldOptions_PB.Ctype ToEnum(long longValue) {
            switch (longValue) {
            
                case 0:
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.Ctype.String;
            
                case 1:
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.Ctype.Cord;
            
                case 2:
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.Ctype.StringPiece;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static string ToString(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "STRING";
            
                case 1:
                    return "CORD";
            
                case 2:
                    return "STRING_PIECE";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
    
        public const long String = 0;
    
        public const long Cord = 1;
    
        public const long StringPiece = 2;
    
    }
}