// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.FieldOptions.FeatureSupport(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB.FieldOptions_PB {

    [System.Serializable]
    public class FeatureSupport {
    
        public string editionIntroduced;
        public global::Google_PB.Protobuf_PB.Edition editionIntroduced_Enum
        {
            get => global::Google_PB.Protobuf_PB.Edition_String.ToEnum(editionIntroduced);
            set => editionIntroduced = global::Google_PB.Protobuf_PB.Edition_String.FromEnum(value);
        }
        public long editionIntroduced_Long
        {
            get => global::Google_PB.Protobuf_PB.Edition_String.ToLong(editionIntroduced);
            set => editionIntroduced = global::Google_PB.Protobuf_PB.Edition_String.FromLong(value);
        }
        
        public string editionDeprecated;
        public global::Google_PB.Protobuf_PB.Edition editionDeprecated_Enum
        {
            get => global::Google_PB.Protobuf_PB.Edition_String.ToEnum(editionDeprecated);
            set => editionDeprecated = global::Google_PB.Protobuf_PB.Edition_String.FromEnum(value);
        }
        public long editionDeprecated_Long
        {
            get => global::Google_PB.Protobuf_PB.Edition_String.ToLong(editionDeprecated);
            set => editionDeprecated = global::Google_PB.Protobuf_PB.Edition_String.FromLong(value);
        }
        
        public string deprecationWarning;
        
        public string editionRemoved;
        public global::Google_PB.Protobuf_PB.Edition editionRemoved_Enum
        {
            get => global::Google_PB.Protobuf_PB.Edition_String.ToEnum(editionRemoved);
            set => editionRemoved = global::Google_PB.Protobuf_PB.Edition_String.FromEnum(value);
        }
        public long editionRemoved_Long
        {
            get => global::Google_PB.Protobuf_PB.Edition_String.ToLong(editionRemoved);
            set => editionRemoved = global::Google_PB.Protobuf_PB.Edition_String.FromLong(value);
        }
        
    }

}