// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.FieldOptions.OptionTargetType(google/protobuf/descriptor.proto)
// </auto-generated>



namespace Google_PB.Protobuf_PB.FieldOptions_PB {

    public enum OptionTargetType {
    
        TargetTypeUnknown = 0,
    
        TargetTypeFile = 1,
    
        TargetTypeExtensionRange = 2,
    
        TargetTypeMessage = 3,
    
        TargetTypeField = 4,
    
        TargetTypeOneof = 5,
    
        TargetTypeEnum = 6,
    
        TargetTypeEnumEntry = 7,
    
        TargetTypeService = 8,
    
        TargetTypeMethod = 9,
    
    }
    public class OptionTargetType_String {
        public static string FromEnum(global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeUnknown:
                    return "TARGET_TYPE_UNKNOWN";
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeFile:
                    return "TARGET_TYPE_FILE";
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeExtensionRange:
                    return "TARGET_TYPE_EXTENSION_RANGE";
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeMessage:
                    return "TARGET_TYPE_MESSAGE";
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeField:
                    return "TARGET_TYPE_FIELD";
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeOneof:
                    return "TARGET_TYPE_ONEOF";
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeEnum:
                    return "TARGET_TYPE_ENUM";
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeEnumEntry:
                    return "TARGET_TYPE_ENUM_ENTRY";
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeService:
                    return "TARGET_TYPE_SERVICE";
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeMethod:
                    return "TARGET_TYPE_METHOD";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static string FromLong(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "TARGET_TYPE_UNKNOWN";
            
                case 1:
                    return "TARGET_TYPE_FILE";
            
                case 2:
                    return "TARGET_TYPE_EXTENSION_RANGE";
            
                case 3:
                    return "TARGET_TYPE_MESSAGE";
            
                case 4:
                    return "TARGET_TYPE_FIELD";
            
                case 5:
                    return "TARGET_TYPE_ONEOF";
            
                case 6:
                    return "TARGET_TYPE_ENUM";
            
                case 7:
                    return "TARGET_TYPE_ENUM_ENTRY";
            
                case 8:
                    return "TARGET_TYPE_SERVICE";
            
                case 9:
                    return "TARGET_TYPE_METHOD";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType ToEnum(string stringValue) {
            switch (stringValue) {
            
                case "TARGET_TYPE_UNKNOWN":
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeUnknown;
            
                case "TARGET_TYPE_FILE":
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeFile;
            
                case "TARGET_TYPE_EXTENSION_RANGE":
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeExtensionRange;
            
                case "TARGET_TYPE_MESSAGE":
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeMessage;
            
                case "TARGET_TYPE_FIELD":
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeField;
            
                case "TARGET_TYPE_ONEOF":
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeOneof;
            
                case "TARGET_TYPE_ENUM":
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeEnum;
            
                case "TARGET_TYPE_ENUM_ENTRY":
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeEnumEntry;
            
                case "TARGET_TYPE_SERVICE":
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeService;
            
                case "TARGET_TYPE_METHOD":
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeMethod;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static long ToLong(string stringValue) {
            switch (stringValue) {
            
                case "TARGET_TYPE_UNKNOWN":
                    return 0;
            
                case "TARGET_TYPE_FILE":
                    return 1;
            
                case "TARGET_TYPE_EXTENSION_RANGE":
                    return 2;
            
                case "TARGET_TYPE_MESSAGE":
                    return 3;
            
                case "TARGET_TYPE_FIELD":
                    return 4;
            
                case "TARGET_TYPE_ONEOF":
                    return 5;
            
                case "TARGET_TYPE_ENUM":
                    return 6;
            
                case "TARGET_TYPE_ENUM_ENTRY":
                    return 7;
            
                case "TARGET_TYPE_SERVICE":
                    return 8;
            
                case "TARGET_TYPE_METHOD":
                    return 9;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
    
        public const string TargetTypeUnknown = "TARGET_TYPE_UNKNOWN";
    
        public const string TargetTypeFile = "TARGET_TYPE_FILE";
    
        public const string TargetTypeExtensionRange = "TARGET_TYPE_EXTENSION_RANGE";
    
        public const string TargetTypeMessage = "TARGET_TYPE_MESSAGE";
    
        public const string TargetTypeField = "TARGET_TYPE_FIELD";
    
        public const string TargetTypeOneof = "TARGET_TYPE_ONEOF";
    
        public const string TargetTypeEnum = "TARGET_TYPE_ENUM";
    
        public const string TargetTypeEnumEntry = "TARGET_TYPE_ENUM_ENTRY";
    
        public const string TargetTypeService = "TARGET_TYPE_SERVICE";
    
        public const string TargetTypeMethod = "TARGET_TYPE_METHOD";
    
    }

    public class OptionTargetType_Long {
        public static long FromEnum(global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeUnknown:
                    return 0;
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeFile:
                    return 1;
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeExtensionRange:
                    return 2;
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeMessage:
                    return 3;
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeField:
                    return 4;
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeOneof:
                    return 5;
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeEnum:
                    return 6;
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeEnumEntry:
                    return 7;
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeService:
                    return 8;
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeMethod:
                    return 9;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static long FromString(string stringValue) {
            switch (stringValue) {
            
                case "TARGET_TYPE_UNKNOWN":
                    return 0;
            
                case "TARGET_TYPE_FILE":
                    return 1;
            
                case "TARGET_TYPE_EXTENSION_RANGE":
                    return 2;
            
                case "TARGET_TYPE_MESSAGE":
                    return 3;
            
                case "TARGET_TYPE_FIELD":
                    return 4;
            
                case "TARGET_TYPE_ONEOF":
                    return 5;
            
                case "TARGET_TYPE_ENUM":
                    return 6;
            
                case "TARGET_TYPE_ENUM_ENTRY":
                    return 7;
            
                case "TARGET_TYPE_SERVICE":
                    return 8;
            
                case "TARGET_TYPE_METHOD":
                    return 9;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType ToEnum(long longValue) {
            switch (longValue) {
            
                case 0:
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeUnknown;
            
                case 1:
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeFile;
            
                case 2:
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeExtensionRange;
            
                case 3:
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeMessage;
            
                case 4:
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeField;
            
                case 5:
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeOneof;
            
                case 6:
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeEnum;
            
                case 7:
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeEnumEntry;
            
                case 8:
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeService;
            
                case 9:
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionTargetType.TargetTypeMethod;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static string ToString(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "TARGET_TYPE_UNKNOWN";
            
                case 1:
                    return "TARGET_TYPE_FILE";
            
                case 2:
                    return "TARGET_TYPE_EXTENSION_RANGE";
            
                case 3:
                    return "TARGET_TYPE_MESSAGE";
            
                case 4:
                    return "TARGET_TYPE_FIELD";
            
                case 5:
                    return "TARGET_TYPE_ONEOF";
            
                case 6:
                    return "TARGET_TYPE_ENUM";
            
                case 7:
                    return "TARGET_TYPE_ENUM_ENTRY";
            
                case 8:
                    return "TARGET_TYPE_SERVICE";
            
                case 9:
                    return "TARGET_TYPE_METHOD";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
    
        public const long TargetTypeUnknown = 0;
    
        public const long TargetTypeFile = 1;
    
        public const long TargetTypeExtensionRange = 2;
    
        public const long TargetTypeMessage = 3;
    
        public const long TargetTypeField = 4;
    
        public const long TargetTypeOneof = 5;
    
        public const long TargetTypeEnum = 6;
    
        public const long TargetTypeEnumEntry = 7;
    
        public const long TargetTypeService = 8;
    
        public const long TargetTypeMethod = 9;
    
    }
}