// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.FieldOptions.OptionRetention(google/protobuf/descriptor.proto)
// </auto-generated>



namespace Google_PB.Protobuf_PB.FieldOptions_PB {

    public enum OptionRetention {
    
        RetentionUnknown = 0,
    
        RetentionRuntime = 1,
    
        RetentionSource = 2,
    
    }
    public class OptionRetention_String {
        public static string FromEnum(global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionRetention enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionRetention.RetentionUnknown:
                    return "RETENTION_UNKNOWN";
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionRetention.RetentionRuntime:
                    return "RETENTION_RUNTIME";
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionRetention.RetentionSource:
                    return "RETENTION_SOURCE";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static string FromLong(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "RETENTION_UNKNOWN";
            
                case 1:
                    return "RETENTION_RUNTIME";
            
                case 2:
                    return "RETENTION_SOURCE";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionRetention ToEnum(string stringValue) {
            switch (stringValue) {
            
                case "RETENTION_UNKNOWN":
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionRetention.RetentionUnknown;
            
                case "RETENTION_RUNTIME":
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionRetention.RetentionRuntime;
            
                case "RETENTION_SOURCE":
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionRetention.RetentionSource;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static long ToLong(string stringValue) {
            switch (stringValue) {
            
                case "RETENTION_UNKNOWN":
                    return 0;
            
                case "RETENTION_RUNTIME":
                    return 1;
            
                case "RETENTION_SOURCE":
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
    
        public const string RetentionUnknown = "RETENTION_UNKNOWN";
    
        public const string RetentionRuntime = "RETENTION_RUNTIME";
    
        public const string RetentionSource = "RETENTION_SOURCE";
    
    }

    public class OptionRetention_Long {
        public static long FromEnum(global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionRetention enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionRetention.RetentionUnknown:
                    return 0;
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionRetention.RetentionRuntime:
                    return 1;
            
                case global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionRetention.RetentionSource:
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static long FromString(string stringValue) {
            switch (stringValue) {
            
                case "RETENTION_UNKNOWN":
                    return 0;
            
                case "RETENTION_RUNTIME":
                    return 1;
            
                case "RETENTION_SOURCE":
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionRetention ToEnum(long longValue) {
            switch (longValue) {
            
                case 0:
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionRetention.RetentionUnknown;
            
                case 1:
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionRetention.RetentionRuntime;
            
                case 2:
                    return global::Google_PB.Protobuf_PB.FieldOptions_PB.OptionRetention.RetentionSource;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static string ToString(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "RETENTION_UNKNOWN";
            
                case 1:
                    return "RETENTION_RUNTIME";
            
                case 2:
                    return "RETENTION_SOURCE";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
    
        public const long RetentionUnknown = 0;
    
        public const long RetentionRuntime = 1;
    
        public const long RetentionSource = 2;
    
    }
}