// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.app.room.play.MoveCardRequest.Move(api/v1/app/room/play/service.proto)
// </auto-generated>

namespace Api_PB.V1_PB.App_PB.Room_PB.Play_PB.MoveCardRequest_PB {

    [System.Serializable]
    public class Move {
    
        public long sourceCardIndex;
        
        public string destinationPlaceId;
        
        public string destinationCardSide;
        public global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side destinationCardSide_Enum
        {
            get => global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side_String.ToEnum(destinationCardSide);
            set => destinationCardSide = global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side_String.FromEnum(value);
        }
        public long destinationCardSide_Long
        {
            get => global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side_String.ToLong(destinationCardSide);
            set => destinationCardSide = global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side_String.FromLong(value);
        }
        
    }

}