// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.FileOptions.OptimizeMode(google/protobuf/descriptor.proto)
// </auto-generated>



namespace Google_PB.Protobuf_PB.FileOptions_PB {

    public enum OptimizeMode {
    
        Speed = 1,
    
        CodeSize = 2,
    
        LiteRuntime = 3,
    
    }
    public class OptimizeMode_String {
        public static string FromEnum(global::Google_PB.Protobuf_PB.FileOptions_PB.OptimizeMode enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.FileOptions_PB.OptimizeMode.Speed:
                    return "SPEED";
            
                case global::Google_PB.Protobuf_PB.FileOptions_PB.OptimizeMode.CodeSize:
                    return "CODE_SIZE";
            
                case global::Google_PB.Protobuf_PB.FileOptions_PB.OptimizeMode.LiteRuntime:
                    return "LITE_RUNTIME";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static string FromLong(long longValue) {
            switch (longValue) {
            
                case 1:
                    return "SPEED";
            
                case 2:
                    return "CODE_SIZE";
            
                case 3:
                    return "LITE_RUNTIME";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.FileOptions_PB.OptimizeMode ToEnum(string stringValue) {
            switch (stringValue) {
            
                case "SPEED":
                    return global::Google_PB.Protobuf_PB.FileOptions_PB.OptimizeMode.Speed;
            
                case "CODE_SIZE":
                    return global::Google_PB.Protobuf_PB.FileOptions_PB.OptimizeMode.CodeSize;
            
                case "LITE_RUNTIME":
                    return global::Google_PB.Protobuf_PB.FileOptions_PB.OptimizeMode.LiteRuntime;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static long ToLong(string stringValue) {
            switch (stringValue) {
            
                case "SPEED":
                    return 1;
            
                case "CODE_SIZE":
                    return 2;
            
                case "LITE_RUNTIME":
                    return 3;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
    
        public const string Speed = "SPEED";
    
        public const string CodeSize = "CODE_SIZE";
    
        public const string LiteRuntime = "LITE_RUNTIME";
    
    }

    public class OptimizeMode_Long {
        public static long FromEnum(global::Google_PB.Protobuf_PB.FileOptions_PB.OptimizeMode enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.FileOptions_PB.OptimizeMode.Speed:
                    return 1;
            
                case global::Google_PB.Protobuf_PB.FileOptions_PB.OptimizeMode.CodeSize:
                    return 2;
            
                case global::Google_PB.Protobuf_PB.FileOptions_PB.OptimizeMode.LiteRuntime:
                    return 3;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static long FromString(string stringValue) {
            switch (stringValue) {
            
                case "SPEED":
                    return 1;
            
                case "CODE_SIZE":
                    return 2;
            
                case "LITE_RUNTIME":
                    return 3;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.FileOptions_PB.OptimizeMode ToEnum(long longValue) {
            switch (longValue) {
            
                case 1:
                    return global::Google_PB.Protobuf_PB.FileOptions_PB.OptimizeMode.Speed;
            
                case 2:
                    return global::Google_PB.Protobuf_PB.FileOptions_PB.OptimizeMode.CodeSize;
            
                case 3:
                    return global::Google_PB.Protobuf_PB.FileOptions_PB.OptimizeMode.LiteRuntime;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static string ToString(long longValue) {
            switch (longValue) {
            
                case 1:
                    return "SPEED";
            
                case 2:
                    return "CODE_SIZE";
            
                case 3:
                    return "LITE_RUNTIME";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
    
        public const long Speed = 1;
    
        public const long CodeSize = 2;
    
        public const long LiteRuntime = 3;
    
    }
}