// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.app.room.play.Place.Type(api/v1/app/room/play/service.proto)
// </auto-generated>



namespace Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Place_PB {

    public enum Type {
    
        TypeUnspecified = 0,
    
        TypeDeck = 1,
    
        TypeHand = 2,
    
        TypeTable = 3,
    
    }
    public class Type_String {
        public static string FromEnum(global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Place_PB.Type enumValue) {
            switch (enumValue) {
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Place_PB.Type.TypeUnspecified:
                    return "TYPE_UNSPECIFIED";
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Place_PB.Type.TypeDeck:
                    return "TYPE_DECK";
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Place_PB.Type.TypeHand:
                    return "TYPE_HAND";
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Place_PB.Type.TypeTable:
                    return "TYPE_TABLE";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static string FromLong(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "TYPE_UNSPECIFIED";
            
                case 1:
                    return "TYPE_DECK";
            
                case 2:
                    return "TYPE_HAND";
            
                case 3:
                    return "TYPE_TABLE";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Place_PB.Type ToEnum(string stringValue) {
            switch (stringValue) {
            
                case "TYPE_UNSPECIFIED":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Place_PB.Type.TypeUnspecified;
            
                case "TYPE_DECK":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Place_PB.Type.TypeDeck;
            
                case "TYPE_HAND":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Place_PB.Type.TypeHand;
            
                case "TYPE_TABLE":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Place_PB.Type.TypeTable;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static long ToLong(string stringValue) {
            switch (stringValue) {
            
                case "TYPE_UNSPECIFIED":
                    return 0;
            
                case "TYPE_DECK":
                    return 1;
            
                case "TYPE_HAND":
                    return 2;
            
                case "TYPE_TABLE":
                    return 3;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
    
        public const string TypeUnspecified = "TYPE_UNSPECIFIED";
    
        public const string TypeDeck = "TYPE_DECK";
    
        public const string TypeHand = "TYPE_HAND";
    
        public const string TypeTable = "TYPE_TABLE";
    
    }

    public class Type_Long {
        public static long FromEnum(global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Place_PB.Type enumValue) {
            switch (enumValue) {
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Place_PB.Type.TypeUnspecified:
                    return 0;
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Place_PB.Type.TypeDeck:
                    return 1;
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Place_PB.Type.TypeHand:
                    return 2;
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Place_PB.Type.TypeTable:
                    return 3;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static long FromString(string stringValue) {
            switch (stringValue) {
            
                case "TYPE_UNSPECIFIED":
                    return 0;
            
                case "TYPE_DECK":
                    return 1;
            
                case "TYPE_HAND":
                    return 2;
            
                case "TYPE_TABLE":
                    return 3;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Place_PB.Type ToEnum(long longValue) {
            switch (longValue) {
            
                case 0:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Place_PB.Type.TypeUnspecified;
            
                case 1:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Place_PB.Type.TypeDeck;
            
                case 2:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Place_PB.Type.TypeHand;
            
                case 3:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Place_PB.Type.TypeTable;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static string ToString(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "TYPE_UNSPECIFIED";
            
                case 1:
                    return "TYPE_DECK";
            
                case 2:
                    return "TYPE_HAND";
            
                case 3:
                    return "TYPE_TABLE";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
    
        public const long TypeUnspecified = 0;
    
        public const long TypeDeck = 1;
    
        public const long TypeHand = 2;
    
        public const long TypeTable = 3;
    
    }
}