// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.MethodOptions.IdempotencyLevel(google/protobuf/descriptor.proto)
// </auto-generated>



namespace Google_PB.Protobuf_PB.MethodOptions_PB {

    public enum IdempotencyLevel {
    
        IdempotencyUnknown = 0,
    
        NoSideEffects = 1,
    
        Idempotent = 2,
    
    }
    public class IdempotencyLevel_String {
        public static string FromEnum(global::Google_PB.Protobuf_PB.MethodOptions_PB.IdempotencyLevel enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.MethodOptions_PB.IdempotencyLevel.IdempotencyUnknown:
                    return "IDEMPOTENCY_UNKNOWN";
            
                case global::Google_PB.Protobuf_PB.MethodOptions_PB.IdempotencyLevel.NoSideEffects:
                    return "NO_SIDE_EFFECTS";
            
                case global::Google_PB.Protobuf_PB.MethodOptions_PB.IdempotencyLevel.Idempotent:
                    return "IDEMPOTENT";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static string FromLong(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "IDEMPOTENCY_UNKNOWN";
            
                case 1:
                    return "NO_SIDE_EFFECTS";
            
                case 2:
                    return "IDEMPOTENT";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.MethodOptions_PB.IdempotencyLevel ToEnum(string stringValue) {
            switch (stringValue) {
            
                case "IDEMPOTENCY_UNKNOWN":
                    return global::Google_PB.Protobuf_PB.MethodOptions_PB.IdempotencyLevel.IdempotencyUnknown;
            
                case "NO_SIDE_EFFECTS":
                    return global::Google_PB.Protobuf_PB.MethodOptions_PB.IdempotencyLevel.NoSideEffects;
            
                case "IDEMPOTENT":
                    return global::Google_PB.Protobuf_PB.MethodOptions_PB.IdempotencyLevel.Idempotent;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static long ToLong(string stringValue) {
            switch (stringValue) {
            
                case "IDEMPOTENCY_UNKNOWN":
                    return 0;
            
                case "NO_SIDE_EFFECTS":
                    return 1;
            
                case "IDEMPOTENT":
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
    
        public const string IdempotencyUnknown = "IDEMPOTENCY_UNKNOWN";
    
        public const string NoSideEffects = "NO_SIDE_EFFECTS";
    
        public const string Idempotent = "IDEMPOTENT";
    
    }

    public class IdempotencyLevel_Long {
        public static long FromEnum(global::Google_PB.Protobuf_PB.MethodOptions_PB.IdempotencyLevel enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.MethodOptions_PB.IdempotencyLevel.IdempotencyUnknown:
                    return 0;
            
                case global::Google_PB.Protobuf_PB.MethodOptions_PB.IdempotencyLevel.NoSideEffects:
                    return 1;
            
                case global::Google_PB.Protobuf_PB.MethodOptions_PB.IdempotencyLevel.Idempotent:
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static long FromString(string stringValue) {
            switch (stringValue) {
            
                case "IDEMPOTENCY_UNKNOWN":
                    return 0;
            
                case "NO_SIDE_EFFECTS":
                    return 1;
            
                case "IDEMPOTENT":
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.MethodOptions_PB.IdempotencyLevel ToEnum(long longValue) {
            switch (longValue) {
            
                case 0:
                    return global::Google_PB.Protobuf_PB.MethodOptions_PB.IdempotencyLevel.IdempotencyUnknown;
            
                case 1:
                    return global::Google_PB.Protobuf_PB.MethodOptions_PB.IdempotencyLevel.NoSideEffects;
            
                case 2:
                    return global::Google_PB.Protobuf_PB.MethodOptions_PB.IdempotencyLevel.Idempotent;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static string ToString(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "IDEMPOTENCY_UNKNOWN";
            
                case 1:
                    return "NO_SIDE_EFFECTS";
            
                case 2:
                    return "IDEMPOTENT";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
    
        public const long IdempotencyUnknown = 0;
    
        public const long NoSideEffects = 1;
    
        public const long Idempotent = 2;
    
    }
}