// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.example.CreateExampleRequest(api/v1/example/example.proto)
// </auto-generated>

namespace Api_PB.V1_PB.Example_PB {

    public class CreateExampleRequest {
    
        public string exampleName;
        
        public string exampleContent;
        
    }

}