// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.example.ListExampleRequest(api/v1/example/example.proto)
// </auto-generated>

namespace Api_PB.V1_PB.Example_PB {

    [System.Serializable]
    public class ListExampleRequest {
    
        public bool desc;
        
        public long limit;
        
        public long offset;
        
    }

}