// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.example.UpdateExampleRequest(api/v1/example/example.proto)
// </auto-generated>

namespace Api_PB.V1_PB.Example_PB {

    public class UpdateExampleRequest {
    
        public string exampleId;
        
        public bool setExampleName;
        
        public string exampleName;
        
        public bool setExampleContent;
        
        public string exampleContent;
        
    }

}