// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.example.UpdateExampleResponse(api/v1/example/example.proto)
// </auto-generated>

namespace Api_PB.V1_PB.Example_PB {

    public class UpdateExampleResponse {
    
        public global::Api_PB.V1_PB.Example_PB.Example example;
        
    }

}