// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.GeneratedCodeInfo.Annotation.Semantic(google/protobuf/descriptor.proto)
// </auto-generated>



namespace Google_PB.Protobuf_PB.GeneratedCodeInfo_PB.Annotation_PB {

    public enum Semantic {
    
        None = 0,
    
        Set = 1,
    
        Alias = 2,
    
    }
    public class Semantic_String {
        public static string FromEnum(global::Google_PB.Protobuf_PB.GeneratedCodeInfo_PB.Annotation_PB.Semantic enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.GeneratedCodeInfo_PB.Annotation_PB.Semantic.None:
                    return "NONE";
            
                case global::Google_PB.Protobuf_PB.GeneratedCodeInfo_PB.Annotation_PB.Semantic.Set:
                    return "SET";
            
                case global::Google_PB.Protobuf_PB.GeneratedCodeInfo_PB.Annotation_PB.Semantic.Alias:
                    return "ALIAS";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static string FromLong(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "NONE";
            
                case 1:
                    return "SET";
            
                case 2:
                    return "ALIAS";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.GeneratedCodeInfo_PB.Annotation_PB.Semantic ToEnum(string stringValue) {
            switch (stringValue) {
            
                case "NONE":
                    return global::Google_PB.Protobuf_PB.GeneratedCodeInfo_PB.Annotation_PB.Semantic.None;
            
                case "SET":
                    return global::Google_PB.Protobuf_PB.GeneratedCodeInfo_PB.Annotation_PB.Semantic.Set;
            
                case "ALIAS":
                    return global::Google_PB.Protobuf_PB.GeneratedCodeInfo_PB.Annotation_PB.Semantic.Alias;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static long ToLong(string stringValue) {
            switch (stringValue) {
            
                case "NONE":
                    return 0;
            
                case "SET":
                    return 1;
            
                case "ALIAS":
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
    
        public const string None = "NONE";
    
        public const string Set = "SET";
    
        public const string Alias = "ALIAS";
    
    }

    public class Semantic_Long {
        public static long FromEnum(global::Google_PB.Protobuf_PB.GeneratedCodeInfo_PB.Annotation_PB.Semantic enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.GeneratedCodeInfo_PB.Annotation_PB.Semantic.None:
                    return 0;
            
                case global::Google_PB.Protobuf_PB.GeneratedCodeInfo_PB.Annotation_PB.Semantic.Set:
                    return 1;
            
                case global::Google_PB.Protobuf_PB.GeneratedCodeInfo_PB.Annotation_PB.Semantic.Alias:
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static long FromString(string stringValue) {
            switch (stringValue) {
            
                case "NONE":
                    return 0;
            
                case "SET":
                    return 1;
            
                case "ALIAS":
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.GeneratedCodeInfo_PB.Annotation_PB.Semantic ToEnum(long longValue) {
            switch (longValue) {
            
                case 0:
                    return global::Google_PB.Protobuf_PB.GeneratedCodeInfo_PB.Annotation_PB.Semantic.None;
            
                case 1:
                    return global::Google_PB.Protobuf_PB.GeneratedCodeInfo_PB.Annotation_PB.Semantic.Set;
            
                case 2:
                    return global::Google_PB.Protobuf_PB.GeneratedCodeInfo_PB.Annotation_PB.Semantic.Alias;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static string ToString(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "NONE";
            
                case 1:
                    return "SET";
            
                case 2:
                    return "ALIAS";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
    
        public const long None = 0;
    
        public const long Set = 1;
    
        public const long Alias = 2;
    
    }
}