{{- /* Go Template */ -}}
// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: {{.SourceFullName}}({{.SourceFile}})
// </auto-generated>

namespace {{.Namespace.Join}} {

    public class {{.ClassName}} {
    {{range .Fields}}
        public {{.FieldType.Type}} {{.FieldName}};
        {{if .FieldType.IsBase64 -}}
        public byte[] {{.FieldName}}_Bytes
        {
            get => global::System.Convert.FromBase64String({{.FieldName}});
            set => {{.FieldName}} = global::System.Convert.ToBase64String(value);
        }
        {{end -}}
        {{if .FieldType.IsTimestamp -}}
        public global::System.DateTime {{.FieldName}}_DateTime
        {
            get => global::System.DateTime.Parse({{.FieldName}});
            set => {{.FieldName}} = value.ToString("o");
        }
        {{end -}}
        {{if .FieldType.EnumTypeName -}}
        public {{.FieldType.EnumTypeName}} {{.FieldName}}_Enum
        {
            get => {{.FieldType.EnumTypeName}}_String.ToEnum({{.FieldName}});
            set => {{.FieldName}} = {{.FieldType.EnumTypeName}}_String.FromEnum(value);
        }
        public long {{.FieldName}}_Long
        {
            get => {{.FieldType.EnumTypeName}}_String.ToLong({{.FieldName}});
            set => {{.FieldName}} = {{.FieldType.EnumTypeName}}_String.FromLong(value);
        }
        {{end -}}
    {{end}}
    }

}