{{- /* Go Template */ -}}
// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: {{.SourceFullName}}({{.SourceFile}})
// </auto-generated>

using UnityEngine;

namespace {{.Namespace.Join}} {

    public partial class {{.ClassName}}
    {

        public class {{.MethodName}}_Result {
            public global::UnityEngine.Networking.UnityWebRequest.Result result;
            public global::{{.Output.Namespace.Join}}.{{.Output.ClassName}} responseBody;
            public global::Api_PB.V1_PB.ErrorResponse errorResponseBody;
        }

        public static async global::Cysharp.Threading.Tasks.UniTask<{{.MethodName}}_Result> {{.MethodName}}(
            global::App.Script.Shared.Api.ISession session,
            global::{{.Input.Namespace.Join}}.{{.Input.ClassName}} input,
            global::System.Collections.Generic.Dictionary<string, string> requestHeaders = null
        )
        {
            string urlPath = {{.HttpInfo.UrlPathTemplate "input"}};
            string urlQuery = {{.HttpInfo.UrlQueryTemplate "input"}};
            var requestUrl = $"{session.GetBaseUrl()}{urlPath}{urlQuery}";

            var inputJson = {{if eq .HttpInfo.Method "GET"}}""{{else}}global::UnityEngine.JsonUtility.ToJson(input){{end}};
            var uwr = new global::UnityEngine.Networking.UnityWebRequest(
                requestUrl,
                "{{.HttpInfo.Method}}",
                new global::UnityEngine.Networking.DownloadHandlerBuffer(),
                new global::UnityEngine.Networking.UploadHandlerRaw(global::System.Text.Encoding.UTF8.GetBytes(inputJson))
            );
            uwr.SetRequestHeader("Content-Type", "application/json");
            requestHeaders = requestHeaders ?? new ();
            requestHeaders = session.AddAuthorization(requestHeaders ?? new ());
            foreach (var header in requestHeaders)
            {
                uwr.SetRequestHeader(header.Key, header.Value);
            }

            session.OnSend(uwr.method, uwr.url, requestHeaders, global::System.Text.Encoding.UTF8.GetString(uwr.uploadHandler.data));
            await uwr.SendWebRequest();
            var outputJson = uwr.downloadHandler.text;
            session.OnReceive(uwr.responseCode, uwr.GetResponseHeaders(), outputJson);

            switch (uwr.result)
            {
                case global::UnityEngine.Networking.UnityWebRequest.Result.Success:
                    return new {{.MethodName}}_Result
                    {
                        result = uwr.result,
                        responseBody = global::UnityEngine.JsonUtility.FromJson<global::{{.Output.Namespace.Join}}.{{.Output.ClassName}}>(outputJson),
                    };
                case global::UnityEngine.Networking.UnityWebRequest.Result.ProtocolError:
                    return new {{.MethodName}}_Result
                    {
                        result = uwr.result,
                        errorResponseBody = global::UnityEngine.JsonUtility.FromJson<global::Api_PB.V1_PB.ErrorResponse>(outputJson),
                    };
                default:
                    return new {{.MethodName}}_Result
                    {
                        result = uwr.result,
                    };
            }
        }
    }

}