{{- /* Go Template */ -}}
// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: {{.SourceFullName}}({{.SourceFile}})
// </auto-generated>

using UnityEngine;

namespace {{.Namespace.Join}} {

    public partial class {{.ClassName}} {
        public class {{.MethodName}} : global::App.Script.Shared.Api.ICaller<global::{{.Output.Namespace.Join}}.{{.Output.ClassName}}> {
            public {{.MethodName}}(
                global::{{.Input.Namespace.Join}}.{{.Input.ClassName}} input,
                global::System.Collections.Generic.Dictionary<string, string> requestHeaders = null
            )
            {
                RequestHeaders = requestHeaders ?? new();
                _input = input;
            }
            private global::{{.Input.Namespace.Join}}.{{.Input.ClassName}} _input;
            public global::System.Collections.Generic.Dictionary<string, string> RequestHeaders { get; private set; }
            public string RequestUrl(string baseUrl)
            {
                string urlPath = {{.HttpInfo.UrlPathTemplate "_input"}};
                string urlQuery = {{.HttpInfo.UrlQueryTemplate "_input"}};
                return $"{baseUrl}{urlPath}{urlQuery}";
            }
            public string RequestBody => global::UnityEngine.JsonUtility.ToJson(_input);
            public global::UnityEngine.Networking.UnityWebRequest.Result CallResult { get; private set; }
            public global::System.Collections.Generic.Dictionary<string, string> ResponseHeaders { get; private set; }
            public long ResponseCode { get; private set; }
            public string ResponseBody { get; private set; }

            public async global::Cysharp.Threading.Tasks.UniTask<global::App.Script.Shared.Api.CallResult<global::{{.Output.Namespace.Join}}.{{.Output.ClassName}}>> Call(string baseUrl)
            {
                global::UnityEngine.Networking.UnityWebRequest uwr;

                try
                {
                    uwr = new global::UnityEngine.Networking.UnityWebRequest(
                        RequestUrl(baseUrl),
                        "{{.HttpInfo.Method}}",
                        new global::UnityEngine.Networking.DownloadHandlerBuffer(),
                        new global::UnityEngine.Networking.UploadHandlerRaw(
                            global::System.Text.Encoding.UTF8.GetBytes(RequestBody))
                    );
                    uwr.SetRequestHeader("Content-Type", "application/json");
                    foreach (var header in RequestHeaders)
                    {
                        uwr.SetRequestHeader(header.Key, header.Value);
                    }

                    await uwr.SendWebRequest();
                }
                catch (System.Exception e)
                {
                    return new global::App.Script.Shared.Api.CallResult<global::{{.Output.Namespace.Join}}.{{.Output.ClassName}}>()
                    {
                        Result = global::UnityEngine.Networking.UnityWebRequest.Result.ConnectionError,
                        ErrorTitle = "Connection Error",
                        ErrorMessage = e.Message,
                    };
                }

                ResponseHeaders = uwr.GetResponseHeaders();
                ResponseCode = uwr.responseCode;
                ResponseBody = uwr.downloadHandler.text;
                switch (uwr.result)
                {
                    case global::UnityEngine.Networking.UnityWebRequest.Result.Success:
                    {
                        try
                        {
                            return new global::App.Script.Shared.Api.CallResult<global::{{.Output.Namespace.Join}}.{{.Output.ClassName}}>()
                            {
                                Result = uwr.result,
                                Value = global::UnityEngine.JsonUtility
                                    .FromJson<global::{{.Output.Namespace.Join}}.{{.Output.ClassName}}>(
                                        ResponseBody)
                            };
                        }
                        catch (System.Exception e)
                        {
                            return new global::App.Script.Shared.Api.CallResult<global::{{.Output.Namespace.Join}}.{{.Output.ClassName}}>()
                            {
                                Result = global::UnityEngine.Networking.UnityWebRequest.Result.DataProcessingError,
                                ErrorTitle = "Invalid Server Response",
                                ErrorMessage = e.Message,
                            };
                        }
                    }
                    case global::UnityEngine.Networking.UnityWebRequest.Result.ProtocolError:
                    {
                        try
                        {
                            return new global::App.Script.Shared.Api.CallResult<global::{{.Output.Namespace.Join}}.{{.Output.ClassName}}>()
                            {
                                Result = uwr.result,
                                ErrorTitle = "Server Return Error",
                                ErrorMessage = uwr.error,
                                ErrorResponse =
                                    global::UnityEngine.JsonUtility.FromJson<global::Api_PB.V1_PB.ErrorResponse>(
                                        ResponseBody),
                            };
                        }
                        catch (System.Exception e)
                        {
                            return new global::App.Script.Shared.Api.CallResult<global::{{.Output.Namespace.Join}}.{{.Output.ClassName}}>()
                            {
                                Result = global::UnityEngine.Networking.UnityWebRequest.Result.DataProcessingError,
                                ErrorTitle = "Invalid Server Response",
                                ErrorMessage = e.Message,
                            };
                        }
                    }
                    default:
                        return new global::App.Script.Shared.Api.CallResult<global::{{.Output.Namespace.Join}}.{{.Output.ClassName}}>()
                        {
                            Result = uwr.result,
                            ErrorTitle = "Unexpected Error",
                            ErrorMessage = uwr.error
                        };
                }
            }
        }
    }
}