// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.app.authentication.PasswordRegisterRequest(api/v1/app/authentication/service.proto)
// </auto-generated>

namespace Api_PB.V1_PB.App_PB.Authentication_PB {

    [System.Serializable]
    public class PasswordRegisterRequest {
    
        public string loginId;
        
        public string password;
        
    }

}