// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.example.ListExampleResponse(api/v1/example/example.proto)
// </auto-generated>

namespace Api_PB.V1_PB.Example_PB {

    [System.Serializable]
    public class ListExampleResponse {
    
        public global::System.Collections.Generic.List<global::Api_PB.V1_PB.Example_PB.Example> exampleList;
        
    }

}