// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.api.CustomHttpPattern(google/api/http.proto)
// </auto-generated>

namespace Google_PB.Api_PB {

    [System.Serializable]
    public class CustomHttpPattern {
    
        public string kind;
        
        public string path;
        
    }

}