// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.api.Http(google/api/http.proto)
// </auto-generated>

namespace Google_PB.Api_PB {

    public class Http {
    
        public global::System.Collections.Generic.List<global::Google_PB.Api_PB.HttpRule> rules;
        
        public bool fullyDecodeReservedExpansion;
        
    }

}