// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.app.room.RoomService.BanMember(api/v1/app/room/service.proto)
// </auto-generated>

using UnityEngine;

namespace Api_PB.V1_PB.App_PB.Room_PB.RoomService_PB {

    public partial class RoomService {
        public class BanMember : global::App.Script.Shared.Api.ICaller<global::Api_PB.V1_PB.App_PB.Room_PB.BanMemberResponse> {
            public BanMember(
                global::Api_PB.V1_PB.App_PB.Room_PB.BanMemberRequest input,
                global::System.Collections.Generic.Dictionary<string, string> requestHeaders = null
            )
            {
                RequestHeaders = requestHeaders ?? new();
                _input = input;
            }
            private global::Api_PB.V1_PB.App_PB.Room_PB.BanMemberRequest _input;
            public global::System.Collections.Generic.Dictionary<string, string> RequestHeaders { get; private set; }
            public string RequestUrl(string baseUrl)
            {
                string urlPath = $"/api/v1/app/room/{(global::UnityEngine.Networking.UnityWebRequest.EscapeURL(_input?.roomId))}/member/{(global::UnityEngine.Networking.UnityWebRequest.EscapeURL(_input?.memberId))}/ban";
                string urlQuery = "";
                return $"{baseUrl}{urlPath}{urlQuery}";
            }
            public string RequestBody => global::UnityEngine.JsonUtility.ToJson(_input);
            public global::UnityEngine.Networking.UnityWebRequest.Result CallResult { get; private set; }
            public global::System.Collections.Generic.Dictionary<string, string> ResponseHeaders { get; private set; }
            public long ResponseCode { get; private set; }
            public string ResponseBody { get; private set; }

            public async global::Cysharp.Threading.Tasks.UniTask<global::App.Script.Shared.Api.CallResult<global::Api_PB.V1_PB.App_PB.Room_PB.BanMemberResponse>> Call(string baseUrl)
            {
                global::UnityEngine.Networking.UnityWebRequest uwr;

                try
                {
                    uwr = new global::UnityEngine.Networking.UnityWebRequest(
                        RequestUrl(baseUrl),
                        "PUT",
                        new global::UnityEngine.Networking.DownloadHandlerBuffer(),
                        new global::UnityEngine.Networking.UploadHandlerRaw(
                            global::System.Text.Encoding.UTF8.GetBytes(RequestBody))
                    );
                    uwr.SetRequestHeader("Content-Type", "application/json");
                    foreach (var header in RequestHeaders)
                    {
                        uwr.SetRequestHeader(header.Key, header.Value);
                    }

                    await uwr.SendWebRequest();
                }
                catch (System.Exception e)
                {
                    return new global::App.Script.Shared.Api.CallResult<global::Api_PB.V1_PB.App_PB.Room_PB.BanMemberResponse>()
                    {
                        Result = global::UnityEngine.Networking.UnityWebRequest.Result.ConnectionError,
                        ErrorTitle = "Connection Error",
                        ErrorMessage = e.Message,
                    };
                }

                ResponseHeaders = uwr.GetResponseHeaders();
                ResponseCode = uwr.responseCode;
                ResponseBody = uwr.downloadHandler.text;
                switch (uwr.result)
                {
                    case global::UnityEngine.Networking.UnityWebRequest.Result.Success:
                    {
                        try
                        {
                            return new global::App.Script.Shared.Api.CallResult<global::Api_PB.V1_PB.App_PB.Room_PB.BanMemberResponse>()
                            {
                                Result = uwr.result,
                                Value = global::UnityEngine.JsonUtility
                                    .FromJson<global::Api_PB.V1_PB.App_PB.Room_PB.BanMemberResponse>(
                                        ResponseBody)
                            };
                        }
                        catch (System.Exception e)
                        {
                            return new global::App.Script.Shared.Api.CallResult<global::Api_PB.V1_PB.App_PB.Room_PB.BanMemberResponse>()
                            {
                                Result = global::UnityEngine.Networking.UnityWebRequest.Result.DataProcessingError,
                                ErrorTitle = "Invalid Server Response",
                                ErrorMessage = e.Message,
                            };
                        }
                    }
                    case global::UnityEngine.Networking.UnityWebRequest.Result.ProtocolError:
                    {
                        try
                        {
                            return new global::App.Script.Shared.Api.CallResult<global::Api_PB.V1_PB.App_PB.Room_PB.BanMemberResponse>()
                            {
                                Result = uwr.result,
                                ErrorTitle = "Server Return Error",
                                ErrorMessage = uwr.error,
                                ErrorResponse =
                                    global::UnityEngine.JsonUtility.FromJson<global::Api_PB.V1_PB.ErrorResponse>(
                                        ResponseBody),
                            };
                        }
                        catch (System.Exception e)
                        {
                            return new global::App.Script.Shared.Api.CallResult<global::Api_PB.V1_PB.App_PB.Room_PB.BanMemberResponse>()
                            {
                                Result = global::UnityEngine.Networking.UnityWebRequest.Result.DataProcessingError,
                                ErrorTitle = "Invalid Server Response",
                                ErrorMessage = e.Message,
                            };
                        }
                    }
                    default:
                        return new global::App.Script.Shared.Api.CallResult<global::Api_PB.V1_PB.App_PB.Room_PB.BanMemberResponse>()
                        {
                            Result = uwr.result,
                            ErrorTitle = "Unexpected Error",
                            ErrorMessage = uwr.error
                        };
                }
            }
        }
    }
}