// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.GeneratedCodeInfo.Annotation(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB.GeneratedCodeInfo_PB {

    public class Annotation {
    
        public global::System.Collections.Generic.List<long> path;
        
        public string sourceFile;
        
        public long begin;
        
        public long end;
        
        public string semantic;
        public global::Google_PB.Protobuf_PB.GeneratedCodeInfo_PB.Annotation_PB.Semantic semantic_Enum
        {
            get => global::Google_PB.Protobuf_PB.GeneratedCodeInfo_PB.Annotation_PB.Semantic_String.ToEnum(semantic);
            set => semantic = global::Google_PB.Protobuf_PB.GeneratedCodeInfo_PB.Annotation_PB.Semantic_String.FromEnum(value);
        }
        public long semantic_Long
        {
            get => global::Google_PB.Protobuf_PB.GeneratedCodeInfo_PB.Annotation_PB.Semantic_String.ToLong(semantic);
            set => semantic = global::Google_PB.Protobuf_PB.GeneratedCodeInfo_PB.Annotation_PB.Semantic_String.FromLong(value);
        }
        
    }

}