// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.FeatureSet.FieldPresence(google/protobuf/descriptor.proto)
// </auto-generated>



namespace Google_PB.Protobuf_PB.FeatureSet_PB {

    public enum FieldPresence {
    
        FieldPresenceUnknown = 0,
    
        Explicit = 1,
    
        Implicit = 2,
    
        LegacyRequired = 3,
    
    }
    public class FieldPresence_String {
        public static string FromEnum(global::Google_PB.Protobuf_PB.FeatureSet_PB.FieldPresence enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.FieldPresence.FieldPresenceUnknown:
                    return "FIELD_PRESENCE_UNKNOWN";
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.FieldPresence.Explicit:
                    return "EXPLICIT";
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.FieldPresence.Implicit:
                    return "IMPLICIT";
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.FieldPresence.LegacyRequired:
                    return "LEGACY_REQUIRED";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static string FromLong(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "FIELD_PRESENCE_UNKNOWN";
            
                case 1:
                    return "EXPLICIT";
            
                case 2:
                    return "IMPLICIT";
            
                case 3:
                    return "LEGACY_REQUIRED";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.FeatureSet_PB.FieldPresence ToEnum(string stringValue) {
            switch (stringValue) {
            
                case "FIELD_PRESENCE_UNKNOWN":
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.FieldPresence.FieldPresenceUnknown;
            
                case "EXPLICIT":
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.FieldPresence.Explicit;
            
                case "IMPLICIT":
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.FieldPresence.Implicit;
            
                case "LEGACY_REQUIRED":
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.FieldPresence.LegacyRequired;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static long ToLong(string stringValue) {
            switch (stringValue) {
            
                case "FIELD_PRESENCE_UNKNOWN":
                    return 0;
            
                case "EXPLICIT":
                    return 1;
            
                case "IMPLICIT":
                    return 2;
            
                case "LEGACY_REQUIRED":
                    return 3;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
    
        public const string FieldPresenceUnknown = "FIELD_PRESENCE_UNKNOWN";
    
        public const string Explicit = "EXPLICIT";
    
        public const string Implicit = "IMPLICIT";
    
        public const string LegacyRequired = "LEGACY_REQUIRED";
    
    }

    public class FieldPresence_Long {
        public static long FromEnum(global::Google_PB.Protobuf_PB.FeatureSet_PB.FieldPresence enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.FieldPresence.FieldPresenceUnknown:
                    return 0;
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.FieldPresence.Explicit:
                    return 1;
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.FieldPresence.Implicit:
                    return 2;
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.FieldPresence.LegacyRequired:
                    return 3;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static long FromString(string stringValue) {
            switch (stringValue) {
            
                case "FIELD_PRESENCE_UNKNOWN":
                    return 0;
            
                case "EXPLICIT":
                    return 1;
            
                case "IMPLICIT":
                    return 2;
            
                case "LEGACY_REQUIRED":
                    return 3;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.FeatureSet_PB.FieldPresence ToEnum(long longValue) {
            switch (longValue) {
            
                case 0:
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.FieldPresence.FieldPresenceUnknown;
            
                case 1:
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.FieldPresence.Explicit;
            
                case 2:
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.FieldPresence.Implicit;
            
                case 3:
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.FieldPresence.LegacyRequired;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static string ToString(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "FIELD_PRESENCE_UNKNOWN";
            
                case 1:
                    return "EXPLICIT";
            
                case 2:
                    return "IMPLICIT";
            
                case 3:
                    return "LEGACY_REQUIRED";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
    
        public const long FieldPresenceUnknown = 0;
    
        public const long Explicit = 1;
    
        public const long Implicit = 2;
    
        public const long LegacyRequired = 3;
    
    }
}