// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.FeatureSet.JsonFormat(google/protobuf/descriptor.proto)
// </auto-generated>



namespace Google_PB.Protobuf_PB.FeatureSet_PB {

    public enum JsonFormat {
    
        JsonFormatUnknown = 0,
    
        Allow = 1,
    
        LegacyBestEffort = 2,
    
    }
    public class JsonFormat_String {
        public static string FromEnum(global::Google_PB.Protobuf_PB.FeatureSet_PB.JsonFormat enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.JsonFormat.JsonFormatUnknown:
                    return "JSON_FORMAT_UNKNOWN";
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.JsonFormat.Allow:
                    return "ALLOW";
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.JsonFormat.LegacyBestEffort:
                    return "LEGACY_BEST_EFFORT";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static string FromLong(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "JSON_FORMAT_UNKNOWN";
            
                case 1:
                    return "ALLOW";
            
                case 2:
                    return "LEGACY_BEST_EFFORT";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.FeatureSet_PB.JsonFormat ToEnum(string stringValue) {
            switch (stringValue) {
            
                case "JSON_FORMAT_UNKNOWN":
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.JsonFormat.JsonFormatUnknown;
            
                case "ALLOW":
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.JsonFormat.Allow;
            
                case "LEGACY_BEST_EFFORT":
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.JsonFormat.LegacyBestEffort;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static long ToLong(string stringValue) {
            switch (stringValue) {
            
                case "JSON_FORMAT_UNKNOWN":
                    return 0;
            
                case "ALLOW":
                    return 1;
            
                case "LEGACY_BEST_EFFORT":
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
    
        public const string JsonFormatUnknown = "JSON_FORMAT_UNKNOWN";
    
        public const string Allow = "ALLOW";
    
        public const string LegacyBestEffort = "LEGACY_BEST_EFFORT";
    
    }

    public class JsonFormat_Long {
        public static long FromEnum(global::Google_PB.Protobuf_PB.FeatureSet_PB.JsonFormat enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.JsonFormat.JsonFormatUnknown:
                    return 0;
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.JsonFormat.Allow:
                    return 1;
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.JsonFormat.LegacyBestEffort:
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static long FromString(string stringValue) {
            switch (stringValue) {
            
                case "JSON_FORMAT_UNKNOWN":
                    return 0;
            
                case "ALLOW":
                    return 1;
            
                case "LEGACY_BEST_EFFORT":
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.FeatureSet_PB.JsonFormat ToEnum(long longValue) {
            switch (longValue) {
            
                case 0:
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.JsonFormat.JsonFormatUnknown;
            
                case 1:
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.JsonFormat.Allow;
            
                case 2:
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.JsonFormat.LegacyBestEffort;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static string ToString(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "JSON_FORMAT_UNKNOWN";
            
                case 1:
                    return "ALLOW";
            
                case 2:
                    return "LEGACY_BEST_EFFORT";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
    
        public const long JsonFormatUnknown = 0;
    
        public const long Allow = 1;
    
        public const long LegacyBestEffort = 2;
    
    }
}