// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.FeatureSet.MessageEncoding(google/protobuf/descriptor.proto)
// </auto-generated>



namespace Google_PB.Protobuf_PB.FeatureSet_PB {

    public enum MessageEncoding {
    
        MessageEncodingUnknown = 0,
    
        LengthPrefixed = 1,
    
        Delimited = 2,
    
    }
    public class MessageEncoding_String {
        public static string FromEnum(global::Google_PB.Protobuf_PB.FeatureSet_PB.MessageEncoding enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.MessageEncoding.MessageEncodingUnknown:
                    return "MESSAGE_ENCODING_UNKNOWN";
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.MessageEncoding.LengthPrefixed:
                    return "LENGTH_PREFIXED";
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.MessageEncoding.Delimited:
                    return "DELIMITED";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static string FromLong(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "MESSAGE_ENCODING_UNKNOWN";
            
                case 1:
                    return "LENGTH_PREFIXED";
            
                case 2:
                    return "DELIMITED";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.FeatureSet_PB.MessageEncoding ToEnum(string stringValue) {
            switch (stringValue) {
            
                case "MESSAGE_ENCODING_UNKNOWN":
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.MessageEncoding.MessageEncodingUnknown;
            
                case "LENGTH_PREFIXED":
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.MessageEncoding.LengthPrefixed;
            
                case "DELIMITED":
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.MessageEncoding.Delimited;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static long ToLong(string stringValue) {
            switch (stringValue) {
            
                case "MESSAGE_ENCODING_UNKNOWN":
                    return 0;
            
                case "LENGTH_PREFIXED":
                    return 1;
            
                case "DELIMITED":
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
    
        public const string MessageEncodingUnknown = "MESSAGE_ENCODING_UNKNOWN";
    
        public const string LengthPrefixed = "LENGTH_PREFIXED";
    
        public const string Delimited = "DELIMITED";
    
    }

    public class MessageEncoding_Long {
        public static long FromEnum(global::Google_PB.Protobuf_PB.FeatureSet_PB.MessageEncoding enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.MessageEncoding.MessageEncodingUnknown:
                    return 0;
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.MessageEncoding.LengthPrefixed:
                    return 1;
            
                case global::Google_PB.Protobuf_PB.FeatureSet_PB.MessageEncoding.Delimited:
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static long FromString(string stringValue) {
            switch (stringValue) {
            
                case "MESSAGE_ENCODING_UNKNOWN":
                    return 0;
            
                case "LENGTH_PREFIXED":
                    return 1;
            
                case "DELIMITED":
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.FeatureSet_PB.MessageEncoding ToEnum(long longValue) {
            switch (longValue) {
            
                case 0:
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.MessageEncoding.MessageEncodingUnknown;
            
                case 1:
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.MessageEncoding.LengthPrefixed;
            
                case 2:
                    return global::Google_PB.Protobuf_PB.FeatureSet_PB.MessageEncoding.Delimited;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static string ToString(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "MESSAGE_ENCODING_UNKNOWN";
            
                case 1:
                    return "LENGTH_PREFIXED";
            
                case 2:
                    return "DELIMITED";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
    
        public const long MessageEncodingUnknown = 0;
    
        public const long LengthPrefixed = 1;
    
        public const long Delimited = 2;
    
    }
}