// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: localdata.LocalData.Server(localdata/localdata.proto)
// </auto-generated>

namespace Localdata_PB.LocalData_PB {

    [System.Serializable]
    public class Server {
    
        public string baseUrl;
        
    }

}