// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: localdata.LocalData.User(localdata/localdata.proto)
// </auto-generated>

namespace Localdata_PB.LocalData_PB {

    [System.Serializable]
    public class User {
    
        public string userId;
        
    }

}