// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.AccessControl(api/v1/access_control.proto)
// </auto-generated>

namespace Api_PB.V1_PB {

    public class AccessControl {
    
        public string scopePath;
        
        public global::System.Collections.Generic.List<string> require;
        
    }

}