// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.ErrorResponse(api/v1/error.proto)
// </auto-generated>

namespace Api_PB.V1_PB {

    public class ErrorResponse {
    
        public string errorCode;
        public global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode errorCode_Enum
        {
            get => global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode_String.ToEnum(errorCode);
            set => errorCode = global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode_String.FromEnum(value);
        }
        public long errorCode_Long
        {
            get => global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode_String.ToLong(errorCode);
            set => errorCode = global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode_String.FromLong(value);
        }
        
        public string errorDescription;
        
        public global::System.Collections.Generic.List<global::Api_PB.V1_PB.ErrorResponse_PB.DataEntry> data;
        
    }

}