// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.JwtPayload(api/v1/jwt.proto)
// </auto-generated>

namespace Api_PB.V1_PB {

    public class JwtPayload {
    
        public long iat;
        
        public long exp;
        
        public string sub;
        
        public string iss;
        
        public string aud;
        
        public string jti;
        
        public string kind;
        public global::Api_PB.V1_PB.JwtPayload_PB.JwtKind kind_Enum
        {
            get => global::Api_PB.V1_PB.JwtPayload_PB.JwtKind_String.ToEnum(kind);
            set => kind = global::Api_PB.V1_PB.JwtPayload_PB.JwtKind_String.FromEnum(value);
        }
        public long kind_Long
        {
            get => global::Api_PB.V1_PB.JwtPayload_PB.JwtKind_String.ToLong(kind);
            set => kind = global::Api_PB.V1_PB.JwtPayload_PB.JwtKind_String.FromLong(value);
        }
        
        public global::Api_PB.V1_PB.JwtPayload_PB.AccessData accessData;
        
        public global::Api_PB.V1_PB.JwtPayload_PB.RefreshData refreshData;
        
    }

}