// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.ClientType(api/v1/client.proto)
// </auto-generated>



namespace Api_PB.V1_PB {

    public enum ClientType {
    
        Unknown = 0,
    
        Web = 1,
    
        Mobile = 2,
    
    }
    public class ClientType_String {
        public static string FromEnum(global::Api_PB.V1_PB.ClientType enumValue) {
            switch (enumValue) {
            
                case global::Api_PB.V1_PB.ClientType.Unknown:
                    return "UNKNOWN";
            
                case global::Api_PB.V1_PB.ClientType.Web:
                    return "WEB";
            
                case global::Api_PB.V1_PB.ClientType.Mobile:
                    return "MOBILE";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static string FromLong(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "UNKNOWN";
            
                case 1:
                    return "WEB";
            
                case 2:
                    return "MOBILE";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static global::Api_PB.V1_PB.ClientType ToEnum(string stringValue) {
            switch (stringValue) {
            
                case "UNKNOWN":
                    return global::Api_PB.V1_PB.ClientType.Unknown;
            
                case "WEB":
                    return global::Api_PB.V1_PB.ClientType.Web;
            
                case "MOBILE":
                    return global::Api_PB.V1_PB.ClientType.Mobile;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static long ToLong(string stringValue) {
            switch (stringValue) {
            
                case "UNKNOWN":
                    return 0;
            
                case "WEB":
                    return 1;
            
                case "MOBILE":
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
    
        public const string Unknown = "UNKNOWN";
    
        public const string Web = "WEB";
    
        public const string Mobile = "MOBILE";
    
    }

    public class ClientType_Long {
        public static long FromEnum(global::Api_PB.V1_PB.ClientType enumValue) {
            switch (enumValue) {
            
                case global::Api_PB.V1_PB.ClientType.Unknown:
                    return 0;
            
                case global::Api_PB.V1_PB.ClientType.Web:
                    return 1;
            
                case global::Api_PB.V1_PB.ClientType.Mobile:
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static long FromString(string stringValue) {
            switch (stringValue) {
            
                case "UNKNOWN":
                    return 0;
            
                case "WEB":
                    return 1;
            
                case "MOBILE":
                    return 2;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static global::Api_PB.V1_PB.ClientType ToEnum(long longValue) {
            switch (longValue) {
            
                case 0:
                    return global::Api_PB.V1_PB.ClientType.Unknown;
            
                case 1:
                    return global::Api_PB.V1_PB.ClientType.Web;
            
                case 2:
                    return global::Api_PB.V1_PB.ClientType.Mobile;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static string ToString(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "UNKNOWN";
            
                case 1:
                    return "WEB";
            
                case 2:
                    return "MOBILE";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
    
        public const long Unknown = 0;
    
        public const long Web = 1;
    
        public const long Mobile = 2;
    
    }
}