// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.app.room.play.Card.Suit(api/v1/app/room/play/service.proto)
// </auto-generated>



namespace Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB {

    public enum Suit {
    
        SuitUnspecified = 0,
    
        SuitHeart = 1,
    
        SuitClub = 2,
    
        SuitDiamond = 3,
    
        SuitSpade = 4,
    
        SuitJoker = 5,
    
    }
    public class Suit_String {
        public static string FromEnum(global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Suit enumValue) {
            switch (enumValue) {
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Suit.SuitUnspecified:
                    return "SUIT_UNSPECIFIED";
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Suit.SuitHeart:
                    return "SUIT_HEART";
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Suit.SuitClub:
                    return "SUIT_CLUB";
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Suit.SuitDiamond:
                    return "SUIT_DIAMOND";
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Suit.SuitSpade:
                    return "SUIT_SPADE";
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Suit.SuitJoker:
                    return "SUIT_JOKER";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static string FromLong(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "SUIT_UNSPECIFIED";
            
                case 1:
                    return "SUIT_HEART";
            
                case 2:
                    return "SUIT_CLUB";
            
                case 3:
                    return "SUIT_DIAMOND";
            
                case 4:
                    return "SUIT_SPADE";
            
                case 5:
                    return "SUIT_JOKER";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Suit ToEnum(string stringValue) {
            switch (stringValue) {
            
                case "SUIT_UNSPECIFIED":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Suit.SuitUnspecified;
            
                case "SUIT_HEART":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Suit.SuitHeart;
            
                case "SUIT_CLUB":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Suit.SuitClub;
            
                case "SUIT_DIAMOND":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Suit.SuitDiamond;
            
                case "SUIT_SPADE":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Suit.SuitSpade;
            
                case "SUIT_JOKER":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Suit.SuitJoker;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static long ToLong(string stringValue) {
            switch (stringValue) {
            
                case "SUIT_UNSPECIFIED":
                    return 0;
            
                case "SUIT_HEART":
                    return 1;
            
                case "SUIT_CLUB":
                    return 2;
            
                case "SUIT_DIAMOND":
                    return 3;
            
                case "SUIT_SPADE":
                    return 4;
            
                case "SUIT_JOKER":
                    return 5;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
    
        public const string SuitUnspecified = "SUIT_UNSPECIFIED";
    
        public const string SuitHeart = "SUIT_HEART";
    
        public const string SuitClub = "SUIT_CLUB";
    
        public const string SuitDiamond = "SUIT_DIAMOND";
    
        public const string SuitSpade = "SUIT_SPADE";
    
        public const string SuitJoker = "SUIT_JOKER";
    
    }

    public class Suit_Long {
        public static long FromEnum(global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Suit enumValue) {
            switch (enumValue) {
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Suit.SuitUnspecified:
                    return 0;
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Suit.SuitHeart:
                    return 1;
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Suit.SuitClub:
                    return 2;
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Suit.SuitDiamond:
                    return 3;
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Suit.SuitSpade:
                    return 4;
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Suit.SuitJoker:
                    return 5;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static long FromString(string stringValue) {
            switch (stringValue) {
            
                case "SUIT_UNSPECIFIED":
                    return 0;
            
                case "SUIT_HEART":
                    return 1;
            
                case "SUIT_CLUB":
                    return 2;
            
                case "SUIT_DIAMOND":
                    return 3;
            
                case "SUIT_SPADE":
                    return 4;
            
                case "SUIT_JOKER":
                    return 5;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Suit ToEnum(long longValue) {
            switch (longValue) {
            
                case 0:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Suit.SuitUnspecified;
            
                case 1:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Suit.SuitHeart;
            
                case 2:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Suit.SuitClub;
            
                case 3:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Suit.SuitDiamond;
            
                case 4:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Suit.SuitSpade;
            
                case 5:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Suit.SuitJoker;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static string ToString(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "SUIT_UNSPECIFIED";
            
                case 1:
                    return "SUIT_HEART";
            
                case 2:
                    return "SUIT_CLUB";
            
                case 3:
                    return "SUIT_DIAMOND";
            
                case 4:
                    return "SUIT_SPADE";
            
                case 5:
                    return "SUIT_JOKER";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
    
        public const long SuitUnspecified = 0;
    
        public const long SuitHeart = 1;
    
        public const long SuitClub = 2;
    
        public const long SuitDiamond = 3;
    
        public const long SuitSpade = 4;
    
        public const long SuitJoker = 5;
    
    }
}