// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.app.authentication.PasswordLoginRequest(api/v1/app/authentication/service.proto)
// </auto-generated>

namespace Api_PB.V1_PB.App_PB.Authentication_PB {

    [System.Serializable]
    public class PasswordLoginRequest {
    
        public string clientType;
        public global::Api_PB.V1_PB.ClientType clientType_Enum
        {
            get => global::Api_PB.V1_PB.ClientType_String.ToEnum(clientType);
            set => clientType = global::Api_PB.V1_PB.ClientType_String.FromEnum(value);
        }
        public long clientType_Long
        {
            get => global::Api_PB.V1_PB.ClientType_String.ToLong(clientType);
            set => clientType = global::Api_PB.V1_PB.ClientType_String.FromLong(value);
        }
        
        public string loginId;
        
        public string password;
        
    }

}