// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.app.authentication.TemporaryRegisterLoginResponse(api/v1/app/authentication/service.proto)
// </auto-generated>

namespace Api_PB.V1_PB.App_PB.Authentication_PB {

    public class TemporaryRegisterLoginResponse {
    
        public string accessToken;
        
        public string refreshToken;
        
    }

}