// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.UninterpretedOption.NamePart(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB.UninterpretedOption_PB {

    public class NamePart {
    
        public string namePart;
        
        public bool isExtension;
        
    }

}