// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.app.user.CreateUserRequest(api/v1/app/user/service.proto)
// </auto-generated>

namespace Api_PB.V1_PB.App_PB.User_PB {

    public class CreateUserRequest {
    
        public string displayName;
        
    }

}