// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.api.HttpRule(google/api/http.proto)
// </auto-generated>

namespace Google_PB.Api_PB {

    [System.Serializable]
    public class HttpRule {
    
        public string selector;
        
        public string get;
        
        public string put;
        
        public string post;
        
        public string delete;
        
        public string patch;
        
        public global::Google_PB.Api_PB.CustomHttpPattern custom;
        
        public string body;
        
        public string responseBody;
        
        public global::System.Collections.Generic.List<global::Google_PB.Api_PB.HttpRule> additionalBindings;
        
    }

}