// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.health.CheckRequest(api/v1/health/service.proto)
// </auto-generated>

namespace Api_PB.V1_PB.Health_PB {

    [System.Serializable]
    public class CheckRequest {
    
    }

}