// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.health.CheckResponse(api/v1/health/service.proto)
// </auto-generated>

namespace Api_PB.V1_PB.Health_PB {

    public class CheckResponse {
    
    }

}