// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.ErrorResponse.DataEntry(api/v1/error.proto)
// </auto-generated>

namespace Api_PB.V1_PB.ErrorResponse_PB {

    [System.Serializable]
    public class DataEntry {
    
        public string key;
        
        public string value;
        
    }

}