// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.ErrorResponse.ErrorCode(api/v1/error.proto)
// </auto-generated>



namespace Api_PB.V1_PB.ErrorResponse_PB {

    public enum ErrorCode {
    
        Unknown = 0,
    
        BadRequest = 1,
    
        PreconditionFailed = 3,
    
        AccessTokenExpired = 4,
    
        RefreshTokenExpired = 5,
    
    }
    public class ErrorCode_String {
        public static string FromEnum(global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode enumValue) {
            switch (enumValue) {
            
                case global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode.Unknown:
                    return "UNKNOWN";
            
                case global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode.BadRequest:
                    return "BAD_REQUEST";
            
                case global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode.PreconditionFailed:
                    return "PRECONDITION_FAILED";
            
                case global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode.AccessTokenExpired:
                    return "ACCESS_TOKEN_EXPIRED";
            
                case global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode.RefreshTokenExpired:
                    return "REFRESH_TOKEN_EXPIRED";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static string FromLong(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "UNKNOWN";
            
                case 1:
                    return "BAD_REQUEST";
            
                case 3:
                    return "PRECONDITION_FAILED";
            
                case 4:
                    return "ACCESS_TOKEN_EXPIRED";
            
                case 5:
                    return "REFRESH_TOKEN_EXPIRED";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode ToEnum(string stringValue) {
            switch (stringValue) {
            
                case "UNKNOWN":
                    return global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode.Unknown;
            
                case "BAD_REQUEST":
                    return global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode.BadRequest;
            
                case "PRECONDITION_FAILED":
                    return global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode.PreconditionFailed;
            
                case "ACCESS_TOKEN_EXPIRED":
                    return global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode.AccessTokenExpired;
            
                case "REFRESH_TOKEN_EXPIRED":
                    return global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode.RefreshTokenExpired;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static long ToLong(string stringValue) {
            switch (stringValue) {
            
                case "UNKNOWN":
                    return 0;
            
                case "BAD_REQUEST":
                    return 1;
            
                case "PRECONDITION_FAILED":
                    return 3;
            
                case "ACCESS_TOKEN_EXPIRED":
                    return 4;
            
                case "REFRESH_TOKEN_EXPIRED":
                    return 5;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
    
        public const string Unknown = "UNKNOWN";
    
        public const string BadRequest = "BAD_REQUEST";
    
        public const string PreconditionFailed = "PRECONDITION_FAILED";
    
        public const string AccessTokenExpired = "ACCESS_TOKEN_EXPIRED";
    
        public const string RefreshTokenExpired = "REFRESH_TOKEN_EXPIRED";
    
    }

    public class ErrorCode_Long {
        public static long FromEnum(global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode enumValue) {
            switch (enumValue) {
            
                case global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode.Unknown:
                    return 0;
            
                case global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode.BadRequest:
                    return 1;
            
                case global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode.PreconditionFailed:
                    return 3;
            
                case global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode.AccessTokenExpired:
                    return 4;
            
                case global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode.RefreshTokenExpired:
                    return 5;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static long FromString(string stringValue) {
            switch (stringValue) {
            
                case "UNKNOWN":
                    return 0;
            
                case "BAD_REQUEST":
                    return 1;
            
                case "PRECONDITION_FAILED":
                    return 3;
            
                case "ACCESS_TOKEN_EXPIRED":
                    return 4;
            
                case "REFRESH_TOKEN_EXPIRED":
                    return 5;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode ToEnum(long longValue) {
            switch (longValue) {
            
                case 0:
                    return global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode.Unknown;
            
                case 1:
                    return global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode.BadRequest;
            
                case 3:
                    return global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode.PreconditionFailed;
            
                case 4:
                    return global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode.AccessTokenExpired;
            
                case 5:
                    return global::Api_PB.V1_PB.ErrorResponse_PB.ErrorCode.RefreshTokenExpired;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static string ToString(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "UNKNOWN";
            
                case 1:
                    return "BAD_REQUEST";
            
                case 3:
                    return "PRECONDITION_FAILED";
            
                case 4:
                    return "ACCESS_TOKEN_EXPIRED";
            
                case 5:
                    return "REFRESH_TOKEN_EXPIRED";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
    
        public const long Unknown = 0;
    
        public const long BadRequest = 1;
    
        public const long PreconditionFailed = 3;
    
        public const long AccessTokenExpired = 4;
    
        public const long RefreshTokenExpired = 5;
    
    }
}