// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.example.ExampleService.ListExample(api/v1/example/example.proto)
// </auto-generated>

using UnityEngine;

namespace Api_PB.V1_PB.Example_PB.ExampleService_PB {

    public partial class ExampleService
    {

        public class ListExample_Result {
            public global::UnityEngine.Networking.UnityWebRequest.Result result;
            public global::Api_PB.V1_PB.Example_PB.ListExampleResponse responseBody;
            public global::Api_PB.V1_PB.ErrorResponse errorResponseBody;
            public string errorMessage;
        }

        public static async global::Cysharp.Threading.Tasks.UniTask<ListExample_Result> ListExample(
            global::App.Script.Shared.Api.ISession session,
            global::Api_PB.V1_PB.Example_PB.ListExampleRequest input,
            global::System.Collections.Generic.Dictionary<string, string> requestHeaders = null
        )
        {
            string urlPath = $"/api/v1/example";
            string urlQuery = $"?{(input?.desc == null ? "" : global::UnityEngine.Networking.UnityWebRequest.EscapeURL($"desc={input?.desc}"))}&{(input?.limit == null ? "" : global::UnityEngine.Networking.UnityWebRequest.EscapeURL($"limit={input?.limit}"))}&{(input?.offset == null ? "" : global::UnityEngine.Networking.UnityWebRequest.EscapeURL($"offset={input?.offset}"))}";
            var requestUrl = $"{session.GetBaseUrl()}{urlPath}{urlQuery}";

            var inputJson = "";
            global::UnityEngine.Networking.UnityWebRequest uwr;

            try
            {
                uwr = new global::UnityEngine.Networking.UnityWebRequest(
                    requestUrl,
                    "GET",
                    new global::UnityEngine.Networking.DownloadHandlerBuffer(),
                    new global::UnityEngine.Networking.UploadHandlerRaw(global::System.Text.Encoding.UTF8.GetBytes(inputJson))
                );
                uwr.SetRequestHeader("Content-Type", "application/json");
                requestHeaders = requestHeaders ?? new ();
                requestHeaders = session.AddAuthorization(requestHeaders ?? new ());
                foreach (var header in requestHeaders)
                {
                    uwr.SetRequestHeader(header.Key, header.Value);
                }

                session.OnSend(uwr.method, uwr.url, requestHeaders, global::System.Text.Encoding.UTF8.GetString(uwr.uploadHandler.data));
                await uwr.SendWebRequest();
            }
            catch (System.Exception e)
            {
                return new ListExample_Result
                {
                    result = global::UnityEngine.Networking.UnityWebRequest.Result.ConnectionError,
                    errorMessage = e.Message,
                };
            }
            var outputJson = uwr.downloadHandler.text;
            session.OnReceive(uwr.responseCode, uwr.GetResponseHeaders(), outputJson);

            switch (uwr.result)
            {
                case global::UnityEngine.Networking.UnityWebRequest.Result.Success:
                {
                    try
                    {
                        return new ListExample_Result {
                            result = uwr.result,
                            responseBody = global::UnityEngine.JsonUtility.FromJson<global::Api_PB.V1_PB.Example_PB.ListExampleResponse>(outputJson)
                        };
                    }
                    catch (System.Exception e)
                    {
                        return new ListExample_Result
                        {
                            result = global::UnityEngine.Networking.UnityWebRequest.Result.DataProcessingError,
                            errorMessage = e.Message,
                        };
                    }
                }
                case global::UnityEngine.Networking.UnityWebRequest.Result.ProtocolError:
                {
                    try
                    {
                        return new ListExample_Result {
                            result = uwr.result,
                            errorResponseBody = global::UnityEngine.JsonUtility.FromJson<global::Api_PB.V1_PB.ErrorResponse>(outputJson),
                            errorMessage = uwr.error,
                        };
                    }
                    catch (System.Exception e)
                    {
                        return new ListExample_Result
                        {
                            result = global::UnityEngine.Networking.UnityWebRequest.Result.DataProcessingError,
                            errorMessage = e.Message,
                        };
                    }
                }
                default:
                    return new ListExample_Result { result = uwr.result, errorMessage = uwr.error };
            }
        }
    }

}