// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.example.ExampleService.GetExample(api/v1/example/example.proto)
// </auto-generated>

using UnityEngine;

namespace Api_PB.V1_PB.Example_PB.ExampleService_PB {

    public partial class ExampleService
    {

        public class GetExample_Result {
            public global::UnityEngine.Networking.UnityWebRequest.Result result;
            public global::Api_PB.V1_PB.Example_PB.GetExampleResponse responseBody;
            public global::Api_PB.V1_PB.ErrorResponse errorResponseBody;
        }

        public static async global::Cysharp.Threading.Tasks.UniTask<GetExample_Result> GetExample(
            global::App.Script.Shared.Api.ISession session,
            global::Api_PB.V1_PB.Example_PB.GetExampleRequest input,
            global::System.Collections.Generic.Dictionary<string, string> requestHeaders = null
        )
        {
            string urlPath = $"/api/v1/example/{(global::UnityEngine.Networking.UnityWebRequest.EscapeURL(input?.exampleId))}";
            string urlQuery = $"?";
            var requestUrl = $"{session.GetBaseUrl()}{urlPath}{urlQuery}";

            var inputJson = "";
            var uwr = new global::UnityEngine.Networking.UnityWebRequest(
                requestUrl,
                "GET",
                new global::UnityEngine.Networking.DownloadHandlerBuffer(),
                new global::UnityEngine.Networking.UploadHandlerRaw(global::System.Text.Encoding.UTF8.GetBytes(inputJson))
            );
            uwr.SetRequestHeader("Content-Type", "application/json");
            requestHeaders = requestHeaders ?? new ();
            requestHeaders = session.AddAuthorization(requestHeaders ?? new ());
            foreach (var header in requestHeaders)
            {
                uwr.SetRequestHeader(header.Key, header.Value);
            }

            session.OnSend(uwr.method, uwr.url, requestHeaders, global::System.Text.Encoding.UTF8.GetString(uwr.uploadHandler.data));
            await uwr.SendWebRequest();
            var outputJson = uwr.downloadHandler.text;
            session.OnReceive(uwr.responseCode, uwr.GetResponseHeaders(), outputJson);

            switch (uwr.result)
            {
                case global::UnityEngine.Networking.UnityWebRequest.Result.Success:
                    return new GetExample_Result
                    {
                        result = uwr.result,
                        responseBody = global::UnityEngine.JsonUtility.FromJson<global::Api_PB.V1_PB.Example_PB.GetExampleResponse>(outputJson),
                    };
                case global::UnityEngine.Networking.UnityWebRequest.Result.ProtocolError:
                    return new GetExample_Result
                    {
                        result = uwr.result,
                        errorResponseBody = global::UnityEngine.JsonUtility.FromJson<global::Api_PB.V1_PB.ErrorResponse>(outputJson),
                    };
                default:
                    return new GetExample_Result
                    {
                        result = uwr.result,
                    };
            }
        }
    }

}