// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.FieldDescriptorProto.Type(google/protobuf/descriptor.proto)
// </auto-generated>



namespace Google_PB.Protobuf_PB.FieldDescriptorProto_PB {

    public enum Type {
    
        TypeDouble = 1,
    
        TypeFloat = 2,
    
        TypeInt64 = 3,
    
        TypeUint64 = 4,
    
        TypeInt32 = 5,
    
        TypeFixed64 = 6,
    
        TypeFixed32 = 7,
    
        TypeBool = 8,
    
        TypeString = 9,
    
        TypeGroup = 10,
    
        TypeMessage = 11,
    
        TypeBytes = 12,
    
        TypeUint32 = 13,
    
        TypeEnum = 14,
    
        TypeSfixed32 = 15,
    
        TypeSfixed64 = 16,
    
        TypeSint32 = 17,
    
        TypeSint64 = 18,
    
    }
    public class Type_String {
        public static string FromEnum(global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeDouble:
                    return "TYPE_DOUBLE";
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeFloat:
                    return "TYPE_FLOAT";
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeInt64:
                    return "TYPE_INT64";
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeUint64:
                    return "TYPE_UINT64";
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeInt32:
                    return "TYPE_INT32";
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeFixed64:
                    return "TYPE_FIXED64";
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeFixed32:
                    return "TYPE_FIXED32";
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeBool:
                    return "TYPE_BOOL";
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeString:
                    return "TYPE_STRING";
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeGroup:
                    return "TYPE_GROUP";
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeMessage:
                    return "TYPE_MESSAGE";
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeBytes:
                    return "TYPE_BYTES";
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeUint32:
                    return "TYPE_UINT32";
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeEnum:
                    return "TYPE_ENUM";
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeSfixed32:
                    return "TYPE_SFIXED32";
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeSfixed64:
                    return "TYPE_SFIXED64";
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeSint32:
                    return "TYPE_SINT32";
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeSint64:
                    return "TYPE_SINT64";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static string FromLong(long longValue) {
            switch (longValue) {
            
                case 1:
                    return "TYPE_DOUBLE";
            
                case 2:
                    return "TYPE_FLOAT";
            
                case 3:
                    return "TYPE_INT64";
            
                case 4:
                    return "TYPE_UINT64";
            
                case 5:
                    return "TYPE_INT32";
            
                case 6:
                    return "TYPE_FIXED64";
            
                case 7:
                    return "TYPE_FIXED32";
            
                case 8:
                    return "TYPE_BOOL";
            
                case 9:
                    return "TYPE_STRING";
            
                case 10:
                    return "TYPE_GROUP";
            
                case 11:
                    return "TYPE_MESSAGE";
            
                case 12:
                    return "TYPE_BYTES";
            
                case 13:
                    return "TYPE_UINT32";
            
                case 14:
                    return "TYPE_ENUM";
            
                case 15:
                    return "TYPE_SFIXED32";
            
                case 16:
                    return "TYPE_SFIXED64";
            
                case 17:
                    return "TYPE_SINT32";
            
                case 18:
                    return "TYPE_SINT64";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type ToEnum(string stringValue) {
            switch (stringValue) {
            
                case "TYPE_DOUBLE":
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeDouble;
            
                case "TYPE_FLOAT":
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeFloat;
            
                case "TYPE_INT64":
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeInt64;
            
                case "TYPE_UINT64":
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeUint64;
            
                case "TYPE_INT32":
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeInt32;
            
                case "TYPE_FIXED64":
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeFixed64;
            
                case "TYPE_FIXED32":
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeFixed32;
            
                case "TYPE_BOOL":
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeBool;
            
                case "TYPE_STRING":
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeString;
            
                case "TYPE_GROUP":
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeGroup;
            
                case "TYPE_MESSAGE":
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeMessage;
            
                case "TYPE_BYTES":
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeBytes;
            
                case "TYPE_UINT32":
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeUint32;
            
                case "TYPE_ENUM":
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeEnum;
            
                case "TYPE_SFIXED32":
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeSfixed32;
            
                case "TYPE_SFIXED64":
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeSfixed64;
            
                case "TYPE_SINT32":
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeSint32;
            
                case "TYPE_SINT64":
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeSint64;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static long ToLong(string stringValue) {
            switch (stringValue) {
            
                case "TYPE_DOUBLE":
                    return 1;
            
                case "TYPE_FLOAT":
                    return 2;
            
                case "TYPE_INT64":
                    return 3;
            
                case "TYPE_UINT64":
                    return 4;
            
                case "TYPE_INT32":
                    return 5;
            
                case "TYPE_FIXED64":
                    return 6;
            
                case "TYPE_FIXED32":
                    return 7;
            
                case "TYPE_BOOL":
                    return 8;
            
                case "TYPE_STRING":
                    return 9;
            
                case "TYPE_GROUP":
                    return 10;
            
                case "TYPE_MESSAGE":
                    return 11;
            
                case "TYPE_BYTES":
                    return 12;
            
                case "TYPE_UINT32":
                    return 13;
            
                case "TYPE_ENUM":
                    return 14;
            
                case "TYPE_SFIXED32":
                    return 15;
            
                case "TYPE_SFIXED64":
                    return 16;
            
                case "TYPE_SINT32":
                    return 17;
            
                case "TYPE_SINT64":
                    return 18;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
    
        public const string TypeDouble = "TYPE_DOUBLE";
    
        public const string TypeFloat = "TYPE_FLOAT";
    
        public const string TypeInt64 = "TYPE_INT64";
    
        public const string TypeUint64 = "TYPE_UINT64";
    
        public const string TypeInt32 = "TYPE_INT32";
    
        public const string TypeFixed64 = "TYPE_FIXED64";
    
        public const string TypeFixed32 = "TYPE_FIXED32";
    
        public const string TypeBool = "TYPE_BOOL";
    
        public const string TypeString = "TYPE_STRING";
    
        public const string TypeGroup = "TYPE_GROUP";
    
        public const string TypeMessage = "TYPE_MESSAGE";
    
        public const string TypeBytes = "TYPE_BYTES";
    
        public const string TypeUint32 = "TYPE_UINT32";
    
        public const string TypeEnum = "TYPE_ENUM";
    
        public const string TypeSfixed32 = "TYPE_SFIXED32";
    
        public const string TypeSfixed64 = "TYPE_SFIXED64";
    
        public const string TypeSint32 = "TYPE_SINT32";
    
        public const string TypeSint64 = "TYPE_SINT64";
    
    }

    public class Type_Long {
        public static long FromEnum(global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type enumValue) {
            switch (enumValue) {
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeDouble:
                    return 1;
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeFloat:
                    return 2;
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeInt64:
                    return 3;
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeUint64:
                    return 4;
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeInt32:
                    return 5;
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeFixed64:
                    return 6;
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeFixed32:
                    return 7;
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeBool:
                    return 8;
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeString:
                    return 9;
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeGroup:
                    return 10;
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeMessage:
                    return 11;
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeBytes:
                    return 12;
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeUint32:
                    return 13;
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeEnum:
                    return 14;
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeSfixed32:
                    return 15;
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeSfixed64:
                    return 16;
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeSint32:
                    return 17;
            
                case global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeSint64:
                    return 18;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static long FromString(string stringValue) {
            switch (stringValue) {
            
                case "TYPE_DOUBLE":
                    return 1;
            
                case "TYPE_FLOAT":
                    return 2;
            
                case "TYPE_INT64":
                    return 3;
            
                case "TYPE_UINT64":
                    return 4;
            
                case "TYPE_INT32":
                    return 5;
            
                case "TYPE_FIXED64":
                    return 6;
            
                case "TYPE_FIXED32":
                    return 7;
            
                case "TYPE_BOOL":
                    return 8;
            
                case "TYPE_STRING":
                    return 9;
            
                case "TYPE_GROUP":
                    return 10;
            
                case "TYPE_MESSAGE":
                    return 11;
            
                case "TYPE_BYTES":
                    return 12;
            
                case "TYPE_UINT32":
                    return 13;
            
                case "TYPE_ENUM":
                    return 14;
            
                case "TYPE_SFIXED32":
                    return 15;
            
                case "TYPE_SFIXED64":
                    return 16;
            
                case "TYPE_SINT32":
                    return 17;
            
                case "TYPE_SINT64":
                    return 18;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type ToEnum(long longValue) {
            switch (longValue) {
            
                case 1:
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeDouble;
            
                case 2:
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeFloat;
            
                case 3:
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeInt64;
            
                case 4:
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeUint64;
            
                case 5:
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeInt32;
            
                case 6:
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeFixed64;
            
                case 7:
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeFixed32;
            
                case 8:
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeBool;
            
                case 9:
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeString;
            
                case 10:
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeGroup;
            
                case 11:
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeMessage;
            
                case 12:
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeBytes;
            
                case 13:
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeUint32;
            
                case 14:
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeEnum;
            
                case 15:
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeSfixed32;
            
                case 16:
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeSfixed64;
            
                case 17:
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeSint32;
            
                case 18:
                    return global::Google_PB.Protobuf_PB.FieldDescriptorProto_PB.Type.TypeSint64;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static string ToString(long longValue) {
            switch (longValue) {
            
                case 1:
                    return "TYPE_DOUBLE";
            
                case 2:
                    return "TYPE_FLOAT";
            
                case 3:
                    return "TYPE_INT64";
            
                case 4:
                    return "TYPE_UINT64";
            
                case 5:
                    return "TYPE_INT32";
            
                case 6:
                    return "TYPE_FIXED64";
            
                case 7:
                    return "TYPE_FIXED32";
            
                case 8:
                    return "TYPE_BOOL";
            
                case 9:
                    return "TYPE_STRING";
            
                case 10:
                    return "TYPE_GROUP";
            
                case 11:
                    return "TYPE_MESSAGE";
            
                case 12:
                    return "TYPE_BYTES";
            
                case 13:
                    return "TYPE_UINT32";
            
                case 14:
                    return "TYPE_ENUM";
            
                case 15:
                    return "TYPE_SFIXED32";
            
                case 16:
                    return "TYPE_SFIXED64";
            
                case 17:
                    return "TYPE_SINT32";
            
                case 18:
                    return "TYPE_SINT64";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
    
        public const long TypeDouble = 1;
    
        public const long TypeFloat = 2;
    
        public const long TypeInt64 = 3;
    
        public const long TypeUint64 = 4;
    
        public const long TypeInt32 = 5;
    
        public const long TypeFixed64 = 6;
    
        public const long TypeFixed32 = 7;
    
        public const long TypeBool = 8;
    
        public const long TypeString = 9;
    
        public const long TypeGroup = 10;
    
        public const long TypeMessage = 11;
    
        public const long TypeBytes = 12;
    
        public const long TypeUint32 = 13;
    
        public const long TypeEnum = 14;
    
        public const long TypeSfixed32 = 15;
    
        public const long TypeSfixed64 = 16;
    
        public const long TypeSint32 = 17;
    
        public const long TypeSint64 = 18;
    
    }
}