// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.app.room.play.Card(api/v1/app/room/play/service.proto)
// </auto-generated>

namespace Api_PB.V1_PB.App_PB.Room_PB.Play_PB {

    [System.Serializable]
    public class Card {
    
        public string side;
        public global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side side_Enum
        {
            get => global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side_String.ToEnum(side);
            set => side = global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side_String.FromEnum(value);
        }
        public long side_Long
        {
            get => global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side_String.ToLong(side);
            set => side = global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.Card_PB.Side_String.FromLong(value);
        }
        
        public string masterCardId;
        
        public string cardRank;
        
        public string cardSuit;
        
    }

}