// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.app.room.play.ListPlaceRequest(api/v1/app/room/play/service.proto)
// </auto-generated>

namespace Api_PB.V1_PB.App_PB.Room_PB.Play_PB {

    [System.Serializable]
    public class ListPlaceRequest {
    
        public string roomId;
        
    }

}