// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: localdata.LocalData(localdata/localdata.proto)
// </auto-generated>

namespace Localdata_PB {

    [System.Serializable]
    public class LocalData {
    
        public global::Localdata_PB.LocalData_PB.Server server;
        
        public global::Localdata_PB.LocalData_PB.Authentication auth;
        
        public global::Localdata_PB.LocalData_PB.User user;
        
    }

}