// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.protobuf.FeatureSetDefaults.FeatureSetEditionDefault(google/protobuf/descriptor.proto)
// </auto-generated>

namespace Google_PB.Protobuf_PB.FeatureSetDefaults_PB {

    [System.Serializable]
    public class FeatureSetEditionDefault {
    
        public string edition;
        public global::Google_PB.Protobuf_PB.Edition edition_Enum
        {
            get => global::Google_PB.Protobuf_PB.Edition_String.ToEnum(edition);
            set => edition = global::Google_PB.Protobuf_PB.Edition_String.FromEnum(value);
        }
        public long edition_Long
        {
            get => global::Google_PB.Protobuf_PB.Edition_String.ToLong(edition);
            set => edition = global::Google_PB.Protobuf_PB.Edition_String.FromLong(value);
        }
        
        public global::Google_PB.Protobuf_PB.FeatureSet overridableFeatures;
        
        public global::Google_PB.Protobuf_PB.FeatureSet fixedFeatures;
        
    }

}