// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api.v1.app.room.play.GetHistoryResponse.HistoryEntry.Operation(api/v1/app/room/play/service.proto)
// </auto-generated>



namespace Api_PB.V1_PB.App_PB.Room_PB.Play_PB.GetHistoryResponse_PB.HistoryEntry_PB {

    public enum Operation {
    
        OperationUnspecified = 0,
    
        OperationCreatePlace = 1,
    
        OperationDeletePlace = 2,
    
        OperationMoveCard = 3,
    
    }
    public class Operation_String {
        public static string FromEnum(global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.GetHistoryResponse_PB.HistoryEntry_PB.Operation enumValue) {
            switch (enumValue) {
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.GetHistoryResponse_PB.HistoryEntry_PB.Operation.OperationUnspecified:
                    return "OPERATION_UNSPECIFIED";
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.GetHistoryResponse_PB.HistoryEntry_PB.Operation.OperationCreatePlace:
                    return "OPERATION_CREATE_PLACE";
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.GetHistoryResponse_PB.HistoryEntry_PB.Operation.OperationDeletePlace:
                    return "OPERATION_DELETE_PLACE";
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.GetHistoryResponse_PB.HistoryEntry_PB.Operation.OperationMoveCard:
                    return "OPERATION_MOVE_CARD";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static string FromLong(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "OPERATION_UNSPECIFIED";
            
                case 1:
                    return "OPERATION_CREATE_PLACE";
            
                case 2:
                    return "OPERATION_DELETE_PLACE";
            
                case 3:
                    return "OPERATION_MOVE_CARD";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.GetHistoryResponse_PB.HistoryEntry_PB.Operation ToEnum(string stringValue) {
            switch (stringValue) {
            
                case "OPERATION_UNSPECIFIED":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.GetHistoryResponse_PB.HistoryEntry_PB.Operation.OperationUnspecified;
            
                case "OPERATION_CREATE_PLACE":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.GetHistoryResponse_PB.HistoryEntry_PB.Operation.OperationCreatePlace;
            
                case "OPERATION_DELETE_PLACE":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.GetHistoryResponse_PB.HistoryEntry_PB.Operation.OperationDeletePlace;
            
                case "OPERATION_MOVE_CARD":
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.GetHistoryResponse_PB.HistoryEntry_PB.Operation.OperationMoveCard;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static long ToLong(string stringValue) {
            switch (stringValue) {
            
                case "OPERATION_UNSPECIFIED":
                    return 0;
            
                case "OPERATION_CREATE_PLACE":
                    return 1;
            
                case "OPERATION_DELETE_PLACE":
                    return 2;
            
                case "OPERATION_MOVE_CARD":
                    return 3;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
    
        public const string OperationUnspecified = "OPERATION_UNSPECIFIED";
    
        public const string OperationCreatePlace = "OPERATION_CREATE_PLACE";
    
        public const string OperationDeletePlace = "OPERATION_DELETE_PLACE";
    
        public const string OperationMoveCard = "OPERATION_MOVE_CARD";
    
    }

    public class Operation_Long {
        public static long FromEnum(global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.GetHistoryResponse_PB.HistoryEntry_PB.Operation enumValue) {
            switch (enumValue) {
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.GetHistoryResponse_PB.HistoryEntry_PB.Operation.OperationUnspecified:
                    return 0;
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.GetHistoryResponse_PB.HistoryEntry_PB.Operation.OperationCreatePlace:
                    return 1;
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.GetHistoryResponse_PB.HistoryEntry_PB.Operation.OperationDeletePlace:
                    return 2;
            
                case global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.GetHistoryResponse_PB.HistoryEntry_PB.Operation.OperationMoveCard:
                    return 3;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(enumValue), enumValue, null);
            }
        }
        public static long FromString(string stringValue) {
            switch (stringValue) {
            
                case "OPERATION_UNSPECIFIED":
                    return 0;
            
                case "OPERATION_CREATE_PLACE":
                    return 1;
            
                case "OPERATION_DELETE_PLACE":
                    return 2;
            
                case "OPERATION_MOVE_CARD":
                    return 3;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(stringValue), stringValue, null);
            }
        }
        public static global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.GetHistoryResponse_PB.HistoryEntry_PB.Operation ToEnum(long longValue) {
            switch (longValue) {
            
                case 0:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.GetHistoryResponse_PB.HistoryEntry_PB.Operation.OperationUnspecified;
            
                case 1:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.GetHistoryResponse_PB.HistoryEntry_PB.Operation.OperationCreatePlace;
            
                case 2:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.GetHistoryResponse_PB.HistoryEntry_PB.Operation.OperationDeletePlace;
            
                case 3:
                    return global::Api_PB.V1_PB.App_PB.Room_PB.Play_PB.GetHistoryResponse_PB.HistoryEntry_PB.Operation.OperationMoveCard;
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
        public static string ToString(long longValue) {
            switch (longValue) {
            
                case 0:
                    return "OPERATION_UNSPECIFIED";
            
                case 1:
                    return "OPERATION_CREATE_PLACE";
            
                case 2:
                    return "OPERATION_DELETE_PLACE";
            
                case 3:
                    return "OPERATION_MOVE_CARD";
            
                default:
                    throw new global::System.ArgumentOutOfRangeException(nameof(longValue), longValue, null);
            }
        }
    
        public const long OperationUnspecified = 0;
    
        public const long OperationCreatePlace = 1;
    
        public const long OperationDeletePlace = 2;
    
        public const long OperationMoveCard = 3;
    
    }
}